### ISSUE TITLE
Schedule Priority addon

### ISSUE THREAD

**Issue by dedu6ka** [ssricardo/anki-plugins#1]
Can you make it interactive? 
User invokes the program thru a (single letter ) shortcut.
Anki will ask the user :  

Enter the Ease; ex:150
 Overdue days taken  into account
 Interval Modifier is 100% 
Proceed ? 
User hits Space-bar or enter.
History Table is updated.

Ex: the last interval was 180,  Overdue was 20d.  
The next interval = ( 180+ 20 ) * 150 = 300  
Thank you.

**Comment by ssricardo** [comment]
Hi.
Sorry for the late reply.

I haven't understood your idea yet. 
Could you try explaining it again?
