### ISSUE TITLE
Problems with many cloze deletions 

### ISSUE THREAD

**Issue by AlejandroEN** [ssricardo/anki-plugins#100]
Hi! 

First of all, thank you very much for developing this fantastic tool, it's a quite useful add-on and now I can't imagine studying without it. 

The problem happens when I have more than 1 cloze deletion: my review UI starts to show the braces of each cloze deletion I've made.

This is what it looks like: 

![image](https://user-images.githubusercontent.com/41605321/130723661-88516216-47df-498b-a91b-c9d066701914.png)

I hope you can fix it. 

Thanks.

**Comment by ssricardo** [comment]
Hi!

That's odd. Guessing I'd say that maybe some hidden character on the card is breaking it, but I need to test.
Could you create a very small deck with this problematic card, and attach it here?

**Comment by AlejandroEN** [comment]
Sure.

Thanks for the help.

[Selected Notes.zip](https://github.com/ssricardo/anki-plugins/files/7048816/Selected.Notes.zip)

**Comment by pedro-volpi** [comment]
I have the exact same problem. I managed to develop a simple example. Just put 18 clozes {{c1::Teste}} in a card. Then change any one of the c1's to c2. You will see that the last cloze shows the braces.

The number of c2 clozes does nothing (unless it's zero), and the position of the c2 tag is irrelevant. It can even be after the last c1 cloze. Also, more c1 clozes will yield more braces.

It's not a special char problem, it's probably a magic number somewhere.
![image](https://user-images.githubusercontent.com/3485085/134418289-49791e89-881a-4dd5-aa6c-19326b401ab6.png)

**Comment by EugeneTarasenko** [comment]
I have the same problem.
<img width="597" alt="Screenshot 2022-03-04 at 01 38 40" src="https://user-images.githubusercontent.com/87163666/156753580-14f6c868-fe11-4804-b2f5-57c1d7bd3a9a.png">

**Comment by ssricardo** [comment]
Hi. 
I can reproduce it with the provided deck. 
Investigating it now...

**Comment by ssricardo** [comment]
Addressed in version 2.7 (10.01.2023)
