### ISSUE TITLE
Issues with right to left languages

### ISSUE THREAD

**Issue by njsteiger** [ssricardo/anki-plugins#101]
It appears that the word shuffler add-on has some issues with languages that are written right to left. Clicking on the words assumes left to right ordering (so only dragging works). And the feedback sentence after you answer is displayed flipped the wrong direction, see attached screenshot.
<img width="663" alt="Screen Shot 2021-09-29 at 12 58 20" src="https://user-images.githubusercontent.com/26658813/135247259-ff4a671c-c50c-4d36-9171-20c746d42fc9.png">

**Comment by njsteiger** [comment]
I fixed this, in my decks, by changing the css styling text direction for this particular cloze deletion note type: "direction: rtl;"

**Comment by ssricardo** [comment]
Hey, great that you found that.
Good for other people to find it as well...

Closing, as there's no need for changes on the implementation.
