### ISSUE TITLE
Note Templates/Styling and error: "Expected to find '{{close:Text}}' or similar in template"

### ISSUE THREAD

**Issue by oliveroliverio** [ssricardo/anki-plugins#102]
Hi, first of all.  Thank you for building this plug-in.  

I'm trying to reproduce your coding example:

``` 
# Title
Rest Service - Method

# Texto
 @Get{{c1::Mapping}}("/something")
public {{c1::ResponseEntry}} handle() {
 String body= ...;
 String etag = ...;
 return {{c1::ResponseEntity}}.ok().eTag(etag).build(body);

# Extra 
@PostMapping
@ResponseStatus(HttpStatus.CREATED)
public void add(@RequestBody
 Person person) {// ...}
```

But your note styling and back template are cutoff from the example.  Do you mind sharing that with us?  I'd really love to style the notes to have that coding syntax.  

Also, a more pressing issue.  I'm getting this error when trying to save this new 'cloze' card template: "Card template 1 in notetype 'cloze' has a problem.  Expected to find '{{close:Text}}' or similar on the front or back of the template."  

Oliver

**Comment by ssricardo** [comment]
Hi Oliver!

I don't use any extra style (so the code doesn't have colored formatting). 

About the second issue, how is your template?
It should be something like _{{type:cloze:Text}}_.

Can try the sample deck and compare yours with it, please:
https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blanks---Starter-Deck

**Comment by ssricardo** [comment]
Closing as inactive. 
If you still have the problem, please reopen it.
