### ISSUE TITLE
It could appear red in case of wrong answer

### ISSUE THREAD

**Issue by S4th1** [ssricardo/anki-plugins#103]
I never know if I got it right or not lol, it's so discreet that I barely notice, if you could make it stand out, I think it could be better

The add-on is very promising, thank you!!!!

**Comment by ssricardo** [comment]
You can change the colors.
Take a look at https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blank---Styles

**Comment by ssricardo** [comment]
Closing, as it's already possible to change it according to link posted
