### ISSUE TITLE
Feature Request: Support multiple {{type:cloze:xxx}} fields

### ISSUE THREAD

**Issue by whosee** [ssricardo/anki-plugins#105]
I have a note with multiple fields: {{Question1}},..., {{QuestionN}} for example. The following would not work as a template:

```
<div class="pick-random">{{type:cloze:Question1}}</div>
...
<div class="pick-random">{{type:cloze:QuestionN}}</div>
```

The use case: 
Random Question for the same answer as in [reddit - multiple rotating](https://www.reddit.com/r/Anki/comments/rcfc21/comment/hnubnvf/?utm_source=share&utm_medium=web2x&context=3)

Thank you for this amazing add-on

**Comment by ssricardo** [comment]
Hi! 
There is already an issue for the same feature: issue #39.

Closing this as duplicate.
