### ISSUE TITLE
Fill in the blanks: Case insensitive for corrections 

### ISSUE THREAD

**Issue by Cristinasj** [ssricardo/anki-plugins#106]
it can be bothersome having to remember whether a word was capitalized or not. 

Great addon, btw

**Comment by ssricardo** [comment]
Hi @Cristinasj!

Have you checked the "feedback-ignore-case" setting?
Or isn't it working correctly?!

**Comment by Cristinasj** [comment]
Oh, sorry, I forgot that I could change it. Thanks! Great addon.
