### ISSUE TITLE
didn't work at all - Ubuntu 20.04

### ISSUE THREAD

**Issue by ghost** [ssricardo/anki-plugins#110]
didn't work for me 
- when I add "type" in front of the {{cloze:fieldname}} - the front of the card disappears completely

I'm on 
Operating system :ubuntu 20.04 
Anki : Version ⁨2.1.48 (fb07bad3)⁩ Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
but the idea is awesome - thank you so much

**Comment by ssricardo** [comment]
Hey @thoraiia !

Probably you are using the wrong note type. It needs to be the cloze one.
Or the template is wrong.

First, even without the add-on (you can disable it), you card should work with Anki "type in the answer". 
Please follow here: https://docs.ankiweb.net/templates/fields.html#checking-your-answer
And search for "type:cloze:". There is also a video mentioned there.

But that works only for a single field per card. 
After that, you can install/enable the addon. And create card with multiple input fields and it should just work.

You can also use this for testing/reference: https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blanks---Starter-Deck

But it does work in Ubuntu, I write/test and use it mostly in Ubuntu.

**Comment by ghost** [comment]
- it's working thank you
- I was using the correct note type 
- it just didn't work in the ( "preview mode" ) which made me think that the add-on is not working 
- but it works just fine in the study mode

**Comment by ssricardo** [comment]
Great! Then I'm closing it

**Comment by ssricardo** [comment]
@thoraiia can you please update the review on Anki Web?!
