### ISSUE TITLE
textarea element 

### ISSUE THREAD

**Issue by vijaykrishnaabba7** [ssricardo/anki-plugins#112]
Can you add a feature like a multiline text area that allows two lines to be typed at the same time?

**Comment by ssricardo** [comment]
Can you suggest how that would be configured?
Like in the card, or in the template? 
Maybe some example...

**Comment by vijaykrishnaabba7** [comment]
for example I want to learn promise from JS
![image](https://user-images.githubusercontent.com/94542271/188931846-eb9d7a13-61a2-45fd-92c6-8c7053d20524.png)

![image](https://user-images.githubusercontent.com/94542271/188931900-351db10e-7a98-4d5c-9be5-e478a45a3bad.png)
![image](https://user-images.githubusercontent.com/94542271/188931909-0c86aa3a-b3aa-4422-9103-3041e4398005.png)


![image](https://user-images.githubusercontent.com/94542271/188931920-7a0a3c67-4ed7-44ca-a7a6-3a3369c97faa.png)

I have added space intentionally at start, when entered with space and without space it's showing error
![image](https://user-images.githubusercontent.com/94542271/188933152-57bcf275-25e0-45f8-acb3-ba3fdcb1e064.png)


![image](https://user-images.githubusercontent.com/94542271/188933159-6cbb7e4b-d5c8-4296-94a0-15f8953824d6.png)

![image](https://user-images.githubusercontent.com/94542271/188933489-d4fab747-08aa-4fc7-9f57-20c175df0ef2.png)



then while learning It will show only One line (that is input)
so instead of input element , can we add textarea element TO enter more lines of answer 
so by this we can learn indentation and syntax
thank you

**Comment by ssricardo** [comment]
Hi! 
I evaluated some requests. In this case, it's possible to get by using separate ones per line. 
And I don't think it'd be good. 
So for, this feature won't be included, ok?!
