### ISSUE TITLE
Typebox size + Audio files + High cloze numbers

### ISSUE THREAD

**Issue by jcznk** [ssricardo/anki-plugins#116]
Hello, first thank you for the great add-on! It really changed my Anki experience for the better.

After some testing, I noticed the following:
1. The typebox changes size depending on the clozed content length. This is useful as it gives you enough space to type what you need, but it is suboptimal in that it gives you an hint about the answer's length. This sometimes results in you knowing exactly the answer, especially when there are more than 1 clozes in the same card with mutually exclusive answers. 
I managed to sort of fix this by setting a maximum width in the template's css, but this prevents the typebox from widening when the placeholder is long. By placeholder I mean e.g. {{c1::example::this is a quite long placeholder}}. I tried looking at the add-ons code without much success as my understanding is limited, then managed to find a workaround by removing the typebox's maximum width on mouseover. I think that some native support would be great though.

2. The add-on does not work well with audio files in the "clozed" field. During reviews,  their names appear instead of the replay button. This happens on the front of the card only and can result in the answer being accidentally revealed, e.g.

![image](https://user-images.githubusercontent.com/60730312/182724247-a0e87068-b811-405b-90d2-ad9d871dc101.png)
You can of course create an extra field for the audio file, but maybe can be addressed without workarounds.

3. The add-on has problem correctly displaying the front of the card when the note contains many clozes. E.g.

![image](https://user-images.githubusercontent.com/60730312/182724879-f375b754-df17-45ed-a7c9-9c4c3c03beff.png)

**Comment by veritasestmoi** [comment]
I'm having the same problems with correctly displaying the front of the card when the note contains many clozes. 

Depending on the length but the smallest number I encountered appearing in the front view is `{{c8:: }}`, I've tried remaking the card but it doesn't help either.

This card contains 17 clozes:

![image](https://user-images.githubusercontent.com/68550874/206906496-c1e85a37-5f35-4b50-829b-045112ecc7e2.png)

**Comment by ssricardo** [comment]
Hopefully solved in the new version, otherwise please re-open:
Addressed in version 2.7 (10.01.2023)
