### ISSUE TITLE
2 issuesdoes not work on mobile.

### ISSUE THREAD

**Issue by cindynap** [ssricardo/anki-plugins#118]
First of all, thanks for this type cloze for me to practice my spelling. I really love it 

However I uninstall it days ago as 
1, Cant use it on Ankidroid. On my mobile, the whole question appears as a cloze. I can't see the question, no answer no practice. 
2, It doesn't support well multiple group clozes such as C1, C2, C3.... Only C1 works.

**Comment by ssricardo** [comment]
Hi @cindynap !

Unfortunately all Anki add'ons support only the desktop version. 
So, nothing specific from this addon, and nothing that I can do about that.

The 2nd point:
actually it supports multiple/distinct cloze on the same card (unless Anki changed something recently and it broke the feature, but I'm not aware).
It's works like any cloze typed card, that is, when studying, the cloze field will be replaced by separate card.

I think there is same example in the sample Deck. 
Can you try it? https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blanks---Starter-Deck

Closing for now, but if you still have some question, just follow up here...

**Comment by cindynap** [comment]
Hi Ricardo, I tried on your sample deck.

This time is even weirder. On the Windows system, the whole front card is
clozed and I can't see the question exactly like on my mobile.

This addon had worked with multi clozes of only 1 group on Anki 2.1.5.4.
Now I am using a new version.

Please check the attachment.

Regards
Cindy


Ricardo ***@***.***> 于2022年9月22日周四 17:18写道：
