### ISSUE TITLE
Only one input showing

### ISSUE THREAD

**Issue by felipekafuri** [ssricardo/anki-plugins#120]
Hey, first of all, pretty cool plugin! I would like to know why it's only showing only one input for me, I don't know what I did wrong. Below are the prints of the card:

<img width="875" alt="Screenshot 2022-12-05 at 19 51 20" src="https://user-images.githubusercontent.com/45128599/205759968-fd74be9c-da73-41b1-bf31-121ad030da6f.png">
<img width="1059" alt="Screenshot 2022-12-05 at 19 51 04" src="https://user-images.githubusercontent.com/45128599/205759997-a7440f61-511f-4fbc-9370-90c522bd0b6f.png">
<img width="1061" alt="Screenshot 2022-12-05 at 19 50 56" src="https://user-images.githubusercontent.com/45128599/205760019-830a723f-6877-493c-96d6-2c275dd3dd91.png">
<img width="1064" alt="Screenshot 2022-12-05 at 19 50 48" src="https://user-images.githubusercontent.com/45128599/205760043-ee3ce894-d4ea-4e5b-b785-4f3c486d713f.png">

**Comment by ssricardo** [comment]
Hi Felipe!
In the card type (template) editor the add-on doesn't run. 
Can you set it up, and try to run on review mode?

**Comment by tommyplusdev** [comment]
I can replicate it if I use `{{c1:: <some text> }}` and `{{c2:: <some text> }}`. 

To get around this, make sure your cloze deletions are all `c1`  => `{{c1:: <some text> }} {{c1:: <some text> }} ... {{c1:: <n text> }}`

You may have to delete the original card if it shows **cloze 2** and remake it with the `c1` in syntax.

**Comment by ssricardo** [comment]
Like I mentioned, it works only in the Reviewer.
In the new version, a warning was added about that: version 2.7 (10.01.2023)
