### ISSUE TITLE
[fill-in-the-blanks] No feedback after pressing answer

### ISSUE THREAD

**Issue by kurkasr** [ssricardo/anki-plugins#122]
Hi. After "Show Answer" cloze disappears in Anki 2.1.55. Not a single letter is shown on the back side and all the input is lost.

**Comment by ssricardo** [comment]
Hi!
But this screenshot seems to be from Anki's default cloze:type cards.
Can you check whether fill-in-the-blanks is indeed enabled? Also try to use the test deck, mentioned in the Wiki page.

There was no recent update in this add-on. But I'll try to test too, with never versions of Anki...

**Comment by ssricardo** [comment]
There is an issue pointed in the issue #124 . I'm on it.

But I'm not sure that it's also your case. 
You mentioned "front card and back card", but it should be with Cloze note types, that is, there is no distinct Front and back.

![Anki_note_type_selection](https://user-images.githubusercontent.com/28906929/211383385-a5fa2863-c767-47db-9c03-441c654479b3.JPG)

**Comment by kurkasr** [comment]
I'm sorry, I meant "front template and back template".
![image](https://user-images.githubusercontent.com/120309744/211492413-90f042f1-c328-4510-86c3-f667207fde05.png)
I think it might be my case.

**Comment by ssricardo** [comment]
Addressed in version 2.7 (10.01.2023)
