### ISSUE TITLE
fill-the-blanks: Nesting cloze input within <div> or element loses cloze input after latest update (Anki 2.5.55/2.5.56)

### ISSUE THREAD

**Issue by tommyplusdev** [ssricardo/anki-plugins#125]
New issue after latest update.

Nesting the cloze within a `<div>` in the card editor makes the cloze feedback input disappear.

<img width="1120" alt="CleanShot 2023-01-10 at 19 49 49@2x" src="https://user-images.githubusercontent.com/116316499/211692646-c8263b83-84b2-478e-bea1-23a0e347fadc.png">

If I try again with no custom card (default cloze type):

<img width="1128" alt="CleanShot 2023-01-10 at 19 54 27@2x" src="https://user-images.githubusercontent.com/116316499/211693262-71e70b1f-48c3-4837-a3ea-d2efb61f28c0.png">

The proper cloze error input shows:

<img width="427" alt="CleanShot 2023-01-10 at 19 55 24@2x" src="https://user-images.githubusercontent.com/116316499/211693123-b8fad098-6883-4acb-b348-4fbfa4c17f52.png">

On the previous plugin update, this worked; see: #124

**Comment by ssricardo** [comment]
I just tested it, wrapping the placeholder in a div like yours, and it works normally. 

Probably you have some other add-on taking part there. 
Could you use https://ankiweb.net/shared/info/31746032, then inspect it and get the actual html?! Then post it here...

**Comment by tommyplusdev** [comment]
Here is the HTML:

![test_1](https://user-images.githubusercontent.com/116316499/211919157-752f32b1-1c42-48a9-8552-291a8598804c.png)
<img width="1655" alt="CleanShot 2023-01-11 at 16 12 11@2x" src="https://user-images.githubusercontent.com/116316499/211919177-95d47443-ab29-42d4-9698-ffe4b8cc3329.png">
<img width="1420" alt="CleanShot 2023-01-11 at 16 12 29@2x" src="https://user-images.githubusercontent.com/116316499/211919184-e03c2e95-f677-4099-9f85-cb8f168894aa.png">

Disabled all add-ons except fill-in-blanks (& web inspector)

**Comment by tommyplusdev** [comment]
The HTML / JS do work as expected;

May be related to #126 , as changing the input to exclude special characters in the cloze does actually make the inputs work, and the timing of the release matches up with both of our issues / use cases

![CleanShot 2023-01-13 at 20 41 02](https://user-images.githubusercontent.com/116316499/212444956-20efc72c-4c54-4b86-8fef-32d71da397f0.png)

Square brackets are also not permitted (alongside the dashes).

![CleanShot 2023-01-13 at 20 45 05](https://user-images.githubusercontent.com/116316499/212445068-236f26ab-593c-459d-bf9c-56643d0216a4.png)

Finally, stripping all unique characters:
![CleanShot 2023-01-13 at 20 45 56](https://user-images.githubusercontent.com/116316499/212445095-ea2e90ff-2eac-48be-98b4-e72188682bcb.png)

I see there is a pending pull request, so that may fix this issue, since I was primarily using it to practice code syntax.

**Comment by ssricardo** [comment]
Yes, I'm planning to test and integrate the existing PR. 
Then check whether it already solves this as well

**Comment by ssricardo** [comment]
The change is released. 
Please check whether it works for you.

**Comment by tommyplusdev** [comment]
The issue is now fixed. The Divs were just a coincidence after all. Square brackets were also tested to be working; this should extend to any unique characters. Thanks to you and lightmotive!
