### ISSUE TITLE
fill-the-blanks: answer comparison missing (blue result after show answer) if the cloze deletion contains several common chars

### ISSUE THREAD

**Issue by lightmotive** [ssricardo/anki-plugins#126]
The following problem makes the Fill in the Blanks add-on unhelpful for code syntax practice, and the latest 2023-01-11 release has extended that long-standing problem to answers that contain only simple characters like quotes and dashes. I've been working around the lack of support for HTML entities within cloze deletions, but I'm now seeking a solution because the latest release extended the problem to many of my cards.

**Card setup:**
<img width="975" alt="image" src="https://user-images.githubusercontent.com/7719153/211866094-eb809328-4a0d-44eb-ba2a-c7d033dad723.png">
*Associated HTML for content above:*
```html
<ul>
  <li>Test 1: {{c1::answer with a to z and 0 to 9 only}}</li>
  <li>Test 2: {{c1::answer with 'single quotes' or "double quotes"}}</li>
  <li>Test 3: {{c1::answer with dash -, plus +, equals =}}</li>
  <li>Test 4: {{c1::answer with &lt;, &gt;, &amp;}}</li>
</ul>
```

**Result after entering *test* for each cloze input and clicking *Show Answer*:**
<img width="947" alt="image" src="https://user-images.githubusercontent.com/7719153/211865316-56fcceef-8893-43da-b396-757732345c5a.png">

After reviewing [handler.py](https://github.com/ssricardo/anki-plugins/blob/d57d0394eac9d4d560751103f4313920fbcf9b85/fill-the-blanks/src/handler.py), I think the problem originates in [this method](https://github.com/ssricardo/anki-plugins/blob/d57d0394eac9d4d560751103f4313920fbcf9b85/fill-the-blanks/src/handler.py#L259), specifically one or more of the multiple strip behaviors. Do you know what's being stripped?

A high-level review process I would expect to behave consistently without reducing security:

1. Set `correctAnswer` to cloze contents as plain text (decode/unescape HTML, other basic processing).
2. Compare `correctAnswer` with what the user typed during their review (already plain text, right?).
3. Encode the comparison result (correct answer or, when answered incorrectly, separate expected and actual elements) as HTML.

What do you think? Please let me know if I can provide more info or help resolve this issue directly. I am a software engineer with deep Ruby knowledge and long-time experience working at high levels with several other languages, though not Python; I think I could help with a little guidance to get started.

**Comment by ssricardo** [comment]
Can you do a test?
Directly in the handler.py in your localhost, try:

1. commenting line 166 (https://github.com/ssricardo/anki-plugins/blob/d57d0394eac9d4d560751103f4313920fbcf9b85/fill-the-blanks/src/handler.py#L166). (Just add a # in the beginning)

Another test: 
2. try moving that line (166) to before line 164

**Comment by lightmotive** [comment]
I only use the MacOS desktop app, so I tested the following using MacOS by editing ~/Library/Application Support/Anki2/addons21/1933645497/handler.py

Here is the answer result when I comment line 166--it fixes the issue with HTML entities:
<img width="942" alt="image" src="https://user-images.githubusercontent.com/7719153/211928122-8de378de-8ea2-4506-90ce-56d4fcc86daf.png">

As you can see, it didn't fix the issues with other common chars. I decided to delve into handler.py to understand what was going on and attempt to fix issues with special characters. I'm happy to report that I identified and fixed some issues while reducing complexity, mostly by changing where `html.escape` is used and tracking the original content in the FieldState class along with `valueAsPlainText`. There was also a need for `re.escape` in one place to support regex-reserved chars within a cloze. I will submit a pull request shortly...

**Comment by ssricardo** [comment]
Merged and released. 
Thanks Andre!

**Comment by lightmotive** [comment]
I was glad to give back. Thank you for creating this useful plugin, Ricardo!
