### ISSUE TITLE
FR: hi, is the priority addon working with 2.1.54, qt6, using scheduler v3?

### ISSUE THREAD

**Issue by ccchan234** [ssricardo/anki-plugins#132]
as it claims work /w scheduler v2.... thanks

**Comment by ccchan234** [comment]
ps, it didn't work /w v2.1.54, v2 engine, qt6.

may be need update or testing, thanks

**Comment by ssricardo** [comment]
Hey! I'll try updating that in the next weeks

**Comment by ssricardo** [comment]
Seems the same problem as issue #134 . 
Closing this one, as the other is more descriptive.

**Comment by ssricardo** [comment]
Version released with small changes.
For Scheduler v3: https://github.com/ssricardo/anki-plugins/wiki/Card-Priority---Scheduler-V3
