### ISSUE TITLE
priority-plugin unreliable.

### ISSUE THREAD

**Issue by ccchan234** [ssricardo/anki-plugins#134]
hi, i made 5 cards, labelled as "cur-card" and made custom study for it.

then they are arranged into highest, high, normal, low, lowest priority; and they are studied using "custom study" for several cycles, in which i always choose "3" i.e. good.

my set of priority is
lv1aaa > lv1aa > lv1a > lv1b > lv1c

but from the result, it seems not reliable:
![image](https://user-images.githubusercontent.com/37549409/235289420-9316b4e6-ed42-4987-9f6c-a0aed511a62a.png)

lv1a got same as lv1c...
lv1b got same as lv1aa

i dont know what's wrong.

thanks

**Comment by ccchan234** [comment]
btw, in the tag, the lower etc are in lower case letters,
while in the addon's config, the 1st letter is capitalized.
makes things complex.

thanks

**Comment by ccchan234** [comment]
another run,

lv1aaa should be the shortest interval?

thanks

![image](https://user-images.githubusercontent.com/37549409/235289725-8424f6cb-5d4c-42de-a760-0dd4e9baa772.png)

**Comment by ccchan234** [comment]
![image](https://user-images.githubusercontent.com/37549409/235312705-fb2620ef-ddab-4ae3-8a58-9be26e72aafa.png)

i use an almost empty portable v2.1.54 qt6 on win,
repeat the above, 
and everycard only have interval of 1 day.

don't know why.

thanks

**Comment by ccchan234** [comment]
from the last 2, 
the lowest and highest priority both get 2 days of interval.
......
![image](https://user-images.githubusercontent.com/37549409/235313812-2abdc192-e3e5-4a55-a891-9608aeb92c7b.png)

**Comment by ccchan234** [comment]
btw, i am on v2 scheluer only, thx

**Comment by ssricardo** [comment]
Hi! 
Thanks for the detailed report.
I already have in mind to update that add-on. Just need to find the time for it. Hopefully soon...

**Comment by ssricardo** [comment]
There's version released today which changed a little the calculated days. More precisely, only how it rounds (it was always rounding low). 

But the point about having the same day repeated is nothing from the add-on, but just normal Anki behaviour. Especially for new cards. 
The add-on simply apply the percentile (according to the configuration) to the value provided by Anki. More preciselly:

> updated time = round("Anki original time" * ("config value matching the priority tag" / 100))

**Comment by ccchan234** [comment]
hi, looks like it worked as expected this time.

i re-do the test as before, always choose "good".
now the timings are reasonable
![image](https://github.com/ssricardo/anki-plugins/assets/37549409/fdf1e206-e5bf-47fb-bd23-45460c1a78b2)

thanks
