### ISSUE TITLE
Problems with tts

### ISSUE THREAD

**Issue by yitzhakbg** [ssricardo/anki-plugins#137]
Front template looks like this:
{{Hebrew}}<br>
{{fill-blanks:cloze:English}}
where Hebrew is the equivalent of Back Extra and English is equivalent of Text (wrapped in curly brackets with C1::)

Back template looks like this:
{{Hebrew}}
\<hr\>
\<!--{{tts en_US:cloze-only:English}}--\>
{{cloze:English}}

Problems:
1. tts reads out twice on the back
2. Placing \<!--{{tts en_US:cloze-only:English}}--\> on the front does nothing whereas \<!--{{tts en_US:cloze:English}}--\> does read out but with "C1 colon colon"

**Comment by ssricardo** [comment]
hmm, that sounds like a very tricky one.
I think, you might do something like using Anki's conditions (like mentioned at https://docs.ankiweb.net/templates/fields.html#hint-fields).

Unfortunately I don't think there's anything that I can do here. 
Therefore, closing...
