### ISSUE TITLE
Fill the Blank compatibility issue with Syntax Highlighting for Code

### ISSUE THREAD

**Issue by ghost** [ssricardo/anki-plugins#14]
Hello, 

First of all thank you for making this add on. It's something I can see being very useful. 

I am currently using the add on syntax highlighting for code (https://ankiweb.net/shared/info/1463041493) to create code snippets in Anki. 

However, when combining fill-the-blanks with the syntax highlighting  add-on I get the issue displayed below

![image](https://user-images.githubusercontent.com/45672545/56829859-d738fb00-6832-11e9-8580-8e55383a5179.png)

The add on works great though when I remove this formatting. The picture below is for the same card with the syntax highlighting removed. 

![image](https://user-images.githubusercontent.com/45672545/56829993-2bdc7600-6833-11e9-8771-2ddfc328a04b.png)

Any ideas? I would love to use these two add-ons together.

**Comment by ssricardo** [comment]
Hey. Thanks for the report.

I'm going to install the *syntax highlighting* here and check that.

-------
I tested with a small piece of code and it worked.
It there any part with regex in your code? I think that might be a limitation. 
Can you attach the code?

**Comment by ghost** [comment]
Hi,

I think that's the issue. Here' the code I was testing it on

![image](https://user-images.githubusercontent.com/45672545/56851500-f2147980-68dd-11e9-8ac0-32b7b52b2975.png)

When I change the cloze to this it works fine

![image](https://user-images.githubusercontent.com/45672545/56852068-5d614a00-68e4-11e9-914a-d34dbde8325d.png)

Please let me know if you find a work-around. I'll be keeping an eye out for any updates!

**Comment by ssricardo** [comment]
I just release version **1.1**.

Please, check the update out!

**Comment by ghost** [comment]
Works great now so far on all the cards I've reviewed. Appreciate the quick update!
