### ISSUE TITLE
Question: Make the n-th input field active by default instead of the first one?

### ISSUE THREAD

**Issue by EugeneTarasenko** [ssricardo/anki-plugins#149]
Hello, I'm currently working on enhancing my card design and optimizing my Anki studying workflow. I'm curious if there's a method to set the n-th (3rd or 5th) input field as active by default instead of the first one.

I have tried using this code but it wouldn't work.

```html
<script>

  var inputs = document.querySelectorAll('input');
  
  inputs[2].focus();

</script>
```

I would appreciate any advice.

![Screenshot 2024-04-01 at 18 58 02](https://github.com/ssricardo/anki-plugins/assets/87163666/209044e0-1dc7-4501-bca8-54208cf4d55e)

**Comment by ssricardo** [comment]
Hey Eugene.
No, that's not supported. 
And it feels like a feature too specific (only for a niche); then it wouldn't worth the time-cost to implement and maintain.
Then I'm closing this, ok?!

If more people have the same need in the future, I can consider adding it...
