### ISSUE TITLE
Web browser - Shortcut problem

### ISSUE THREAD

**Issue by ssricardo** [ssricardo/anki-plugins#22]
From ankiweb:

 the shortcut is not working.. it crashed my anki many times, tried to change it, no use...

**Comment by ssricardo** [comment]
Did it happen with which shortcut (show menu or repeat last one)?

What is the environment (Anki version, Operational System...)

**Comment by JORDENmaker** [comment]
I have the same problem when im clicking the right button to upload a google image, it just doesn't give me the option to get google image web site. faiils

**Comment by ssricardo** [comment]
@JORDENmaker could you copy the error information showed by Anki?

**Comment by Nanco300** [comment]
> @JORDENmaker could you copy the error information showed by Anki?

Dont't appear any information.

**Comment by ssricardo** [comment]
Closing with version 2.0 adjustment. 
Please, reopen if it persists
