### ISSUE TITLE
Option to turn off purple bar

### ISSUE THREAD

**Issue by pchhina** [ssricardo/anki-plugins#24]
Thanks for the add-on, it's really useful. 

I have one request - if the purple bar (indicating area where markdown is being applied) can be made optional (may be in preferences) ?

I would not mind if it only shows in the previews, but it  also shows up in card reviews which is distracting.

Thanks,
Param

**Comment by ssricardo** [comment]
Hi!
I think I can take a look to disable that in the next days...

But do you only use this addon for preview?
