### ISSUE TITLE
Error occurred 

### ISSUE THREAD

**Issue by doneskii** [ssricardo/anki-plugins#25]
![image](https://user-images.githubusercontent.com/53286486/61844024-024fdc80-ae6c-11e9-81ca-fdef1503181c.png)

Will randomly get this error when I search a word for an image or web search. If I restart the card I'm trying to make by exiting out and then starting a new card the addon will run normally again until a few more searches later the random error appears. Using a mac so idk if that makes a diff

**Comment by ssricardo** [comment]
Humm.
That's a little hard to track.

Does it happen when you start editing a card and leave it still for while, then try to continue later?
Or do you see any pattern? For any specific website?

**Comment by doneskii** [comment]
> Humm.
> That's a little hard to track.
> 
> Does it happen when you start editing a card and leave it still for while, then try to continue later?
> Or do you see any pattern? For any specific website?
I only use google web/image. It happens randomly...haven't noticed any patterns, but it's happening more frequently than before

**Comment by ssricardo** [comment]
Hi.
As this refers to an old version, and it has no activities lately, I'll close it. 
Open a new one if the same still happen on the newest version
