### ISSUE TITLE
how to install "Fill the blanks", Anki 2.1?

### ISSUE THREAD

**Issue by xorowist** [ssricardo/anki-plugins#26]
i tried to install your plugin on clear Anki (2.1.14 Qt 5.12.1 PyQt 5.11.3).
What add-ons still need to be installed in anki for your plugin to work?
Your plugin in the pictures looks very good, but it is not clear how to install it...

**Comment by ssricardo** [comment]
Hi!
The installation is pretty much a standard Anki addon (that: Tools -> add-ons -> Get... and put the code).

Now, to have those *input fields* on your card, you need to use an Anki Feature called *type:cloze*. 
Search that term on the [manual](https://apps.ankiweb.net/docs/manual.html).

Basically, you need to edit the card template:
> Tools -> Manage Note Types -> (select the desired) -> Card

Then replace where it's just `{{cloze:FieldName}}` with `{{type:cloze:FieldName}}`

**Comment by ssricardo** [comment]
Let me know if you got it!

**Comment by xorowist** [comment]
> Let me know if you got it!

i solved the problem. 
The problem was that in my language of Anki the string
{{cloze:FieldName}} is {{cloze:Текст}}

i just copy-past ur string: {{type:cloze:FieldName}}
i should write {{type:cloze:Текст}}

![2019-07-31_12-59-13](https://user-images.githubusercontent.com/12018762/62203138-46267280-b393-11e9-8d3f-ef0a6c591ebd.png)

but now i have another problem... ur addon is "case sensitive", is that easy to fix it?
nice job mate! is there a thumbs up on github?

![2019-07-31_13-03-13](https://user-images.githubusercontent.com/12018762/62203519-03b16580-b394-11e9-9883-b8f60cc1ab07.png)

**Comment by ssricardo** [comment]
Great! I'm glad it worked.

The case sensitivity is not a problem, but just the normal way it works, As it checks whether the text is equals to the input. But don't you worry, it's already planned to make it optional (configurable).

As this ticket was about setting it up, I'm closing it.
