### ISSUE TITLE
[web browser] Suggested feature: sort in config

### ISSUE THREAD

**Issue by galantra** [ssricardo/anki-plugins#28]
![grafik](https://user-images.githubusercontent.com/52420923/62866957-6c90ca00-bd12-11e9-8053-cc1992d90f9f.png)
I think it would be great to add a function to sort the providers. This would make the number shortcuts more accessible.

**Comment by ssricardo** [comment]
Hi! 
Good idea!
Now I'm already about to release a new version of this addon (this week), so this won't be present yet. 
But I'll keep it for some of the next releases

**Comment by ssricardo** [comment]
Done! Version 3.0
