### ISSUE TITLE
[web browser] suggested feature: keep html when pasting

### ISSUE THREAD

**Issue by galantra** [ssricardo/anki-plugins#29]
When I copy & paste from Firefox, the html will be maintained in the anki add window.
Is this also possible with the add-on?

**Comment by ssricardo** [comment]
Sorry, I couldn't understand well the idea. 
Can you try to explain a little more?!

**Comment by galantra** [comment]
Yes, sure. Let me give an example:
Suppose you want to copy a text with line breaks, like my post:

> When I copy & paste from Firefox, the html will be maintained in the anki add window.
> Is this also possible with the add-on?

When I copy this into a card using the web browser add-on, it will result in:
> When I copy & paste from Firefox, the html will be maintained in the anki add window.Is this also possible with the add-on?

I think the reason for the omission of the line break is this: The add-on disregards html.
Therefore, I propose we include copy and paste of html to preserve line breaks and even more intricate formatting.

**Comment by galantra** [comment]
Yet I do think it's not an urgent feature since ctrl+c, ctrl+v of the highlighted content is almost as quick. You may well discard the thought.

**Comment by ssricardo** [comment]
I tried to do it, but I couldn't (with the tech stack used on this addon and Anki).
It's also possible to drag and drop as formatted...

Then, closing as there are no plans to work more on that for now...
