### ISSUE TITLE
How to identify the cards I'm checking with your addon?

### ISSUE THREAD

**Issue by cjdduarte** [ssricardo/anki-plugins#3]
How to identify the cards I'm checking with your addon?
The question is to know during the study, if that card is "modified" by its addon.

**Comment by ssricardo** [comment]
This is an interesting issue.
For now, you need to use some other addon that shows the tags on the card.
It would be good to know that without rely on other addons though. 
Do you have any idea on how could I show that infomation?

**Comment by ssricardo** [comment]
Done! Version: 1.2

It was added a message on bottom-right part of the Answer card. 
It says like "Priority: High". 
If it's Normal (not modified), nothing is shown.

**Comment by cjdduarte** [comment]
Tanks
