### ISSUE TITLE
Cloze hint option Error!!

### ISSUE THREAD

**Issue by Pdact** [ssricardo/anki-plugins#31]
I got error when i used hint option for Cloze in ANKI
Example:
Field1: {{c1::kündigen::kün...}}

then Anki show me this in Preview window
->kündigen + <typing window> + kündigen::kün...

Anki give me double Field1 and one typing window
Can you help me fix this? Thank you

**Comment by Pdact** [comment]
![image](https://user-images.githubusercontent.com/54911068/64285368-f02d8780-cf5b-11e9-8cd0-194eb653c642.png)
Anki makes this
![image](https://user-images.githubusercontent.com/54911068/64285388-fe7ba380-cf5b-11e9-8c5c-451ccc8ce484.png)
Without your Plugin
![image](https://user-images.githubusercontent.com/54911068/64285801-8eb9e880-cf5c-11e9-931f-93868a4b9605.png)
By the way can you add one option to work with multiple Clozes? like this
Probleme mit der Sprache ->> {{c1::Probleme::Pro...}} {{c2::mit::mi...}} {{c1::der::de...}} {{c2::Sprache::Spr...}}
i really appreciate it 👯‍♂ 

Thank you very much!!!

**Comment by ssricardo** [comment]
I didn't even know that Anki has that feature. So it wasn't considered on this addon.

I'll take a look for a future release, but it won't be very soon. Now I'm working on a now addon...

**Comment by Pdact** [comment]
That is wonderful, i'm waiting for your Update ! thank you! and wish you have a nice day 💃

**Comment by ssricardo** [comment]
Done! Version 1.5
