### ISSUE TITLE
suggested feature: click on one or more words to search instead of highlighting

### ISSUE THREAD

**Issue by B-bit-maker** [ssricardo/anki-plugins#35]
First of all, thank you for the Web Browser add-on.
I have a feature to suggest:
Instead of highlighting, would it be possible to click on the word(s) to search? In my opinion that would make it faster to search images, especially when the query to search is composed of nonadjacent words in a sentence. For example, let's say I'm studying English and I have this sentence to find an image for:

His eyes are blue

Instead of searching only 'eyes' or 'blue', I think it would be better to search both words on Google Images. As of now, there's no way to do that, since I can't select multiple words in Anki (and even if I could, it wouldn't be very efficient).

The way to do that could be similar to what the author of this add-on did (https://ankiweb.net/shared/info/754868802 , see the screenshot that shows the "word select" tab). It could be a separated tab where a specific field is shown (in this case the one containing the whole sentence) with the single words clickable, so that clicking on the word x would start the search (on Google Images for example) for x, and clicking later on the word y would start the search for 'x y'.

This would be similar to what the Fluent Forever app already offers.

Regards

**Comment by ssricardo** [comment]
Hey!
Thanks for the suggestion!
I'll take a look on it, but it could take same time, as it may require some major changes internally...

**Comment by B-bit-maker** [comment]
Ok, thanks.

**Comment by ssricardo** [comment]
Considering alternatives, since this change would be hard...
What about if we configure a set of words to be ignored, like "are, the, her"... 

@B-bit-maker would this be useful for your cases?

**Comment by B-bit-maker** [comment]
Thank you for your reply.
Yes, it would be useful. In that case, the process of adding words to those to be ignored should be quick, like 2-3 clicks, or a keyboard shortcut, as opening the add-on options every time you want to add a new word to the list would be too slow.

**Comment by ssricardo** [comment]
The implementation (of those filtered words) was already on its way using the config windows.
Now check out also the "no selection options".

Closing it with the work around options on version 3.0
