### ISSUE TITLE
Markdown Addon will throw errors sometimes on clicking decks in browser

### ISSUE THREAD

**Issue by JiaChen-Zeng** [ssricardo/anki-plugins#36]
Hi. I am new to the addon for 2 days and it has occurred 2 times so far.

I think it is when switching decks in the browser window, the error sometimes will occur.

```
Debug info:
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 322, in handler
  File "aqt\editor.py", line 331, in oncallback
  File "anki\hooks.py", line 29, in runHook
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\1259478414\controller.py", line 206, in onLoadNote
    self.setEditAsMarkdownEnabled(self._editAsMarkdownEnabled)  # initialization
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\1259478414\controller.py", line 260, in setEditAsMarkdownEnabled
    self._editorReference.web.eval('editAsMarkdownEnabled = {};'.format(str(value).lower())) # check is it needed?
<class 'AttributeError'>: 'NoneType' object has no attribute 'eval'
```

## EDIT

The error occurs also when switching off the `Edit as Markdown`. Before it occurs, the card shows in `Customize Card Templates` window won't render markdown despite `Edit as Markdown`is on.

**Comment by ssricardo** [comment]
Hi @M-Azuma !

That's odd, I'll try to check. But do you use other addons that may affect Anki's editor?

**Comment by JiaChen-Zeng** [comment]
Hi. 

I think `Mini Format Pack` and `Japanese Support` might affect it. Maybe I'll try to disable other addons and see.

**Comment by ssricardo** [comment]
Hey @M-Azuma , do you know whether this still happens after last update?

**Comment by JiaChen-Zeng** [comment]
Sorry, I am not using the plugin recently so I don't know.

**Comment by ssricardo** [comment]
Hey! No problem...

Then I'll close this, as there were already many changes.

Thanks!
