### ISSUE TITLE
Extremely useful but the usage is a bit inconvenient

### ISSUE THREAD

**Issue by scarphin** [ssricardo/anki-plugins#37]
Hi,
First of all, thank you for this plugin. This was something I was hoping to come by for a while now yet you did a very good job with this. However in my humble opinion the usage is extremely indirect. Let me explain in 2 topics:
1- I don't see a reason why this plugin cannot be used during reviewing the cards other than technical reasons. For example in my case I have decks including over 2000 notes which I have studied all (unfortunately before finding this plugin, maybe even before this plugin existed). What I need to do now is to go to the deck in question and attach images 1 by 1. Honestly that's not practical for me because I have cards that are due say 9 months in the deck. I don't want to go through all those cards at the same time and if possible I'd like to attach pictures when I review them which is less boring and practical imo.
2- There are no default values. What I mean by this is, user has to copy some word to look it up. Really? In browser window of Anki that is one of the last things I want to do. Looking up for the copied text is fine but my suggestion is if there is no copied text why not look up the text in a default field that can be configured in the config menu of the plugin? Say 'Expression' for example, in my entire deck collection every vocabulary note has that field containing the word to be studied. It's also very ease to configure the notes this way. Also for inserting the image into the card, instead of right clicking and picking a menu item to insert, can Ctrl-click or something be used to insert the image again into a default field (i.e 'Image') configured through addon config? Those 2 will bring the total actions down to 3:
a- Click the shortcut,
b- Pick the image,
c- Ctrl-click, middle click whatever, insert the image.

Again this is a great plugin but if you can consider this improvements it would be much more practical.

Thank you...

**Comment by ssricardo** [comment]
Hey!
Ok, many requests... some I think are good ideas, but some of them maybe would just add complexity to maintain it. 
I'll take them into consideration when I get some time...

**Comment by ssricardo** [comment]
Some improvements to shorten its use are now available, on version 3.0.
