### ISSUE TITLE
Fill the blank add-on - New feature: Support multiple distinct fields

### ISSUE THREAD

**Issue by izanagiii** [ssricardo/anki-plugins#39]
Hi
thanks for your great add-ons

**Some insights:** 
It would be great if you just could modify the way add-on is used in a card template (e.g {{Fill:cloze}} instead of {{type:cloze}}) so we can have anki's original type cloze function (with comma seperator) which can be used with different fields as overlapper and a special note type for just using your add-on. 

This way we can have both of them based on our needs, for example for details in a code snippets we use the note type that uses your add-on & for overlap cloze which asks about some of those details at once we could use native type cloze.

**e.g.** what I need: to be asked for different size clozes based on the same text
**1st Field:**
{{c1::import}} time
{{c1::import}} datetime
{{c1::import}} os

**2nd Field:**
{{c2::import time}}
{{c3::import datetime}}
{{c4::import os}}

since I use different clozes as ovelapper the add-on breaks & shows both of them in {{front}}, I think changing the way the add-on is activated in note template would be a temporary solution.

Good job and thanks a lot

**Comment by ssricardo** [comment]
Distinct prefix added in today's version.
Details: https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blanks-New-Integration
