### ISSUE TITLE
wont work on mobile

### ISSUE THREAD

**Issue by JeromeChallet** [ssricardo/anki-plugins#4]
big thank you for doing his but when sync with iphone, about 80 to 90% of the pictures wont show up, sync media is checked on both side and i never have this issue if i import a pic from my desktop.

also when i go into edit mode on my iphone the pictures are visible there

any help?

thank you

**Comment by ssricardo** [comment]
Thanks for reporting it, @jrme421 . 
That's a weird behavior. I'll take a look as soon as I have time!

**Comment by ssricardo** [comment]
@jrme421 on Android (AnkiDroid) it is working. Unfortunately I don't have an iPhone to test that.
Can you test again with a different image/link?

Or maybe it's a problem with the Iphone version of Anki, otherwise it wouldn't work on Android either.

**Comment by ssricardo** [comment]
Closing duo to lack of response
