### ISSUE TITLE
anki-web-browser

### ISSUE THREAD

**Issue by izanagiii** [ssricardo/anki-plugins#40]
HI
**thanks** for your contribution to anki community

It would be great if you could add these feature:
1. add an **drag & drop** feature (like as I do drag picture from chrome to my anki fields ) 
2. add download support (e.g. in forvo we can just play the **audio** not to download it nor input to fiels)
3. add an option to **rearrange** our urls (e.g I want collins dictionary at the top)

With these changes the add-on lacks nothing

**Great** job
thanks again

**Comment by ssricardo** [comment]
Hi!

Thanks for those ideas, some of them already under development...

**Comment by ssricardo** [comment]
From your suggestions:

1. I spent some time trying that but I couldn't make it work; so dropping the idea for while.
2. No plans related to this. The forvo example, afaik that the way it works normally (on any web browser)
3. Done! (update to version 3.0)
