### ISSUE TITLE
Fill-in-blank Bug

### ISSUE THREAD

**Issue by izanagiii** [ssricardo/anki-plugins#42]
Hi
**Thanks for your life saving add-on**

unfortunately cloze numbers more than 10 are not correctly shown in your add-on, It seems there is a cap/limit to number of cloze deletion.
However it works fine and this problem is just a matter of showing it correct not functionality.

It would be great if you could address this issue

Best regards

Pictures:
![error 2](https://user-images.githubusercontent.com/59202302/71798332-e5e4dc80-3066-11ea-919a-4b8fbac1d2a8.JPG)
![error 1](https://user-images.githubusercontent.com/59202302/71798342-f09f7180-3066-11ea-9824-461342f6406c.JPG)

**Comment by ssricardo** [comment]
Done! Version 1.5

**Comment by izanagiii** [comment]
> Done! Version 1.5

Thanks man, much appreciated
