### ISSUE TITLE
fill-in-blank suggestion

### ISSUE THREAD

**Issue by izanagiii** [ssricardo/anki-plugins#43]
Hi
your add-on is Great for code snippets

**Some insights**: 
It would be great if you just could modify the way add-on is used in a card template (e.g {{typem:cloze}} instead of {{type:cloze}}) so we can have anki's original type multiple cloze function (with comma seperator) that can be used with different fields as overlapper and a special note type for just using your add-on.

This way we can have both of them based on our needs, for example for details in a code snippets we use the note type that uses your add-on & for overlap cloze which asks about some of those details at once we could use native type cloze.

Good job and thanks a lot

**Comment by ssricardo** [comment]
Hey!

Isn't this the same as you reported here?
https://github.com/ssricardo/anki-plugins/issues/39

**Comment by izanagiii** [comment]
Yeah Sorry my bad 

I didn't remember I posted this request earlier

sorry, my memory is not good thats why I need Anki

**Comment by ssricardo** [comment]
Closing as repeated
