### ISSUE TITLE
Sound does not play in the front card

### ISSUE THREAD

**Issue by pespinozav** [ssricardo/anki-plugins#45]
The card shows the name of the file instead of playing the sound when using type in the answer Cloze deletions. It works correctly with the Basic card type. It also works with the Cloze deletion (the one without Cloze deletion).

{{c2::John}} said {{c1::phonology}}.
[sound:phonology--_gb_1.mp3]

![image](https://user-images.githubusercontent.com/22034819/72777834-d53a7780-3bcb-11ea-947e-4bd70584ed17.png)

The sound does play once I press "Answer"

**Comment by ssricardo** [comment]
I can remove the file name, during the "question" phase. 
But Anki originally doesn't play audio on type cards. For now, I wouldn't be able to do it; ok?!

**Comment by ssricardo** [comment]
Done! Version 1.5

**Comment by pespinozav** [comment]
I think I updated the file: clicked on Check for Updates, and then it says that "Fill the blanks -- Multiple typecloze support" had an update... so I said ok and then restarted Anki. 
However, the behavior seems to be the same: 
![image](https://user-images.githubusercontent.com/22034819/73316627-55726580-41e8-11ea-9da2-4768b86ae52b.png)
Then I changed the type of the card to Cloze -- instead of Cloze (Type in the answer) -- and I got what I think the expected behavior should be:
The **sound played** and the name of the file did not show:
![image](https://user-images.githubusercontent.com/22034819/73316814-0a0c8700-41e9-11ea-802e-61849c2d25dc.png)
The files appear to be new so I think the update did take: 
![image](https://user-images.githubusercontent.com/22034819/73316901-46d87e00-41e9-11ea-9f03-32e49237e565.png)
Hopefully I'm not missing anything obvious! 
Best.

**Comment by ssricardo** [comment]
Yeah, actually I know already what's the problem...
I considered the file name with only letters, numbers and dot. 
I'll update it, taking _ and - into consideration also...

**Comment by ssricardo** [comment]
New version 1.6. 

Please check again.

**Comment by pespinozav** [comment]
The name of the file no longer shows up. Thanks!

However, I still think the intended behavior is to play the sound when the card appears; that is the behavior when I use the Cloze type. I would like to hear the word that I'm learning, and then type it into the box to check that I'm able to recognize the word and spell it correctly. Makes sense?

**Comment by ssricardo** [comment]
Yes, it makes sense. 
But that will require major changes over Anki's code. 
In the moment I don't have the time needed for that, but I'll keep this in mind, to try creating this in the future.

**Comment by pespinozav** [comment]
Got it. Thanks for explaining the status.

**Comment by pespinozav** [comment]
I still miss this feature. Is the issue closed because it was resolved ? I went to **Duplicando texto #54** but my Portuguese is.... well... it is not there yet.
Thanks!

**Comment by pespinozav** [comment]
I was able to translate the other post and I noticed that the response says that this is an issue with Anki.  Maybe we are not talking about the same?
If I change the type of the Note in question  to Basic, the sound on the first card **does play**, so it would seem that Anki does support sound on the first card of Note.
I'm probably missing something.... thanks!
