### ISSUE TITLE
notes with more than 9 cloze view in fill in blank

### ISSUE THREAD

**Issue by izanagiii** [ssricardo/anki-plugins#46]
Hi 
Thanks again for your contribution & the recent update 

unfortunately even after your recent update that problem with showing the clozes more than 9 still persist:

here is the screenshot:
![error 1](https://user-images.githubusercontent.com/59202302/73606189-24fe4300-45bd-11ea-960b-945cec13cc7c.JPG)

Best regards

**Comment by ssricardo** [comment]
Humm.. :/
Ok, I'll check it again

**Comment by izanagiii** [comment]
It will be so kind of you

Best regards

**Comment by ssricardo** [comment]
Hey @izanagiii .

I just tested with 11 clozes and it worked.

Tested with:

```public class RestClient {
  
    private static final String REST_URI 
      = "http://localhost/resources/employees";
  
    private {{c7::Client}} client = {{c1::ClientBuilder}}.{{c2::newClient}}();
 
    public Employee getJsonEmployee(int id) {
        return client
          .{{c3::target}}(REST_URI)
          .{{c4::path}}(String.valueOf(id))
          .{{c5::request}}(MediaType.APPLICATION_JSON)
          .{{c6::get}}(Employee.class);
    }
    //...

  // post({{c8::Entity}}.{{c9::entity}}(emp, {{c10::MediaType}}.{{c11::APPLICATION_JSON}})
}
```

How is it rendering on your case?

**Comment by izanagiii** [comment]
Hi
Thanks for checking it again

Strangely the problem is resolved now!!! have you updated the add-on again?

1st: I tested the coded you mentioned & the result was correct?
![1](https://user-images.githubusercontent.com/59202302/75625796-b7066500-5bd6-11ea-847a-f3cd82d13890.JPG)

2nd: I create a note with my own code which had a problem on showing more than 9 clozes & suprisingly this time the result was correct!!!
![2](https://user-images.githubusercontent.com/59202302/75625794-aeae2a00-5bd6-11ea-99fb-67a93c7ef651.JPG)

Thanks again for your add-on
Looking forward for more feature because this add-on is a must in learning programming with anki

**Comment by ssricardo** [comment]
Well, great then...
I haven't updated it in the last days, so it was probably just some detail on your installation after updating it.

Closing, as it's solved...
