### ISSUE TITLE
Feature request: ignore accents in feedback - option

### ISSUE THREAD

**Issue by ghost** [ssricardo/anki-plugins#48]
Hi! Great addon, for sure.

This is about the Multiple type:cloze support.
I use it for learning languages and do not always switch the keyboard layout, making me often ignore typing in the accents because it goes faster for me. It is often just a hassle to type it. This however turns an immediate false in the feedback when I omit the accent. I know that some purists probably want to have the accents properly recognized. So I would suggest an option in the feedback configuration, similar to the case sensitive option. If TRUE, ignore accents.

Example if ignore accents = TRUE
alemán = green
aleman = green

Example if ignore accents = FALSE
alemán = green
aleman = red (starting when typing the "a" without the accent)

Would be great to see this.

**Comment by ssricardo** [comment]
Done! Released with version 1.7

**Comment by ghost** [comment]
awesome, works like a charm. Thank you!
