### ISSUE TITLE
can't specify additionnal term in the search url

### ISSUE THREAD

**Issue by Sabeurre** [ssricardo/anki-plugins#5]
Thanks for the add on, unfortunately, I just discovered some limitations that were not present in the previous anki 2.0 version "Search Google Images for selected words"

Say I want to obtain contextual images with the selected word, for example, "selected word"+puppy,  "selected word"+cat, or "selected word"+アニメ美少女
I would write https://www.google.co.jp/search?tbm=isch&q={}+アニメ美少女
But the add-on refuses it, saying URL is invalid because "{}" isn't present. 
Any fix ?
Thank you.

**Comment by ssricardo** [comment]
Fixed on version 1.1
