### ISSUE TITLE
Help please.

### ISSUE THREAD

**Issue by DoctorToBeIn23** [ssricardo/anki-plugins#51]
How would I write this code in, is it possible? I have this website downloaded into files on my computer... 
Download link: https://usmlebookspdf.com/download-uptodate-2018-edition-full-offline-free/
file:///Users/Jacob/Desktop/Medical%20School%20Desktop/UpToDate%202018/d/search.htm?s=

**Comment by DoctorToBeIn23** [comment]
And or how would I write this one in?
https://www-uptodate-com.proxy.rvu.edu/contents/search

**Comment by ssricardo** [comment]
I haven't got exactly the question...
do you want to use "fill the blanks" for codes?

If so, have you tried to follow the instructions here?
https://github.com/ssricardo/anki-plugins/tree/master/fill-the-blanks

**Comment by DoctorToBeIn23** [comment]
Sorry I thought this was "Web Browser - Search terms, Import texts and images automatically" https://ankiweb.net/shared/info/864545277. I know you are the author to that add on, would you mind taking a look?

**Comment by ssricardo** [comment]
Oh, actually both addons are in this repository. 
I just didn't understand which one you were referring to.

I think (maybe) I got it now. You want to use that website (https://www-uptodate-com.proxy.rvu.edu/contents/search) as provider. Is that it?!

If so, it works if the website has an address with the term to be searched. For instance, if it's like this:

> https://www-uptodate-com.proxy.rvu.edu/contents/search/MySearch

Otherwise, unfortunately it's not supported. Because on this case, the website uses some internal way to search things and I can't use their way...

If you can search something and take/send me a printscreen, I can verify whether the website provides an address like I mentioned before or not...

**Comment by DoctorToBeIn23** [comment]
I searched "hello" 
https://www-uptodate-com.proxy.rvu.edu/contents/search?search=hello&sp=0&searchType=PLAIN_TEXT&source=USER_INPUT&searchControl=TOP_PULLDOWN&searchOffset=1&autoComplete=false&language=&max=0&index=&autoCompleteTerm=

I also have the website downloaded so I have access to it offline, I also searched hello, let me know if either would work... :) Thank you for your help!!!

file:///Users/Jacob/Desktop/Medical%20School%20Desktop/UpToDate%202018/d/search.htm?s=hello

**Comment by ssricardo** [comment]
Try with:

> https://www-uptodate-com.proxy.rvu.edu/contents/search?search={}&sp=0&searchType=PLAIN_TEXT&source=USER_INPUT&searchControl=TOP_PULLDOWN&searchOffset=1&autoComplete=false&language=&max=0&index=&autoCompleteTerm=

and 

> file:///Users/Jacob/Desktop/Medical%20School%20Desktop/UpToDate%202018/d/search.htm?s={}

Basically, you need to replace the term with {}

**Comment by DoctorToBeIn23** [comment]
The proxy worked but the downloaded website in files didnt, do you know if
the add on will pull up files like how I want it?

>

**Comment by ssricardo** [comment]
I think then, that referencing the files directly as file:// isn't supported. 
To use files on your computer, you would need to emulate a server.

You can try something like:
* https://themeisle.com/blog/how-to-host-a-website/
* https://1stwebdesigner.com/local-web-server/

**Comment by DoctorToBeIn23** [comment]
Thanks for the help!!

**Comment by DoctorToBeIn23** [comment]
Last question, when I search the Uptodate website it makes me log in each
time. Is there a way to save my username/password or have it automatically
log in?

**Comment by ssricardo** [comment]
Humm... I think between Anki sessions (when you close Anki) it won't be possible to keep it. 
But within one session, I think it's supposed to keep it.

The add-on itself doesn't control anything regarding this...
