### ISSUE TITLE
Unable to see this note type

### ISSUE THREAD

**Issue by DataSciLearner** [ssricardo/anki-plugins#53]
HI,
I am not sure if I'm stupidly missing the obvious. I have installed the add on "fill in the blank's" in my Anki and re-started the software. But I am not able to find the card type from the drop-down list that corresponds to this “fill in the blanks” card type.  I have the latest Anki. What am I doing wrong? Please help.

**Comment by ssricardo** [comment]
Hi!

The addon doesn't create a new card type. Instead, it replaces Anki behavior for cards with type:cloze (which by default allows only one big field per card).

Search "type:cloze" on https://apps.ankiweb.net/docs/manual.html. 
Or take a look on https://www.youtube.com/watch?v=5tYObQ3ocrw&yt%3Acc=on

**Comment by DataSciLearner** [comment]
> Hi!
> 
> The addon doesn't create a new card type. Instead, it replaces Anki behavior for cards with type:cloze (which by default allows only one big field per card).
> 
> Search "type:cloze" on https://apps.ankiweb.net/docs/manual.html.
> Or take a look on https://www.youtube.com/watch?v=5tYObQ3ocrw&yt%3Acc=on

Thank you very much for the detailed video.  I have another question: When I have multiple cloze deletions, I am able to have only cloze deletion that I'm able to type into (following your video guidelines). Is that to be the case, or am I doing something wrong? See attached the screenshots. 
Thank you for your time and help.
![image](https://user-images.githubusercontent.com/8789867/75031578-7c961d00-549e-11ea-9a92-aa4198e54409.png)
![image](https://user-images.githubusercontent.com/8789867/75031618-92a3dd80-549e-11ea-8861-c142e208c46c.png)
![image](https://user-images.githubusercontent.com/8789867/75031684-b8c97d80-549e-11ea-980b-b6cf8d6875fe.png)

**Comment by ssricardo** [comment]
@DataSciLearner you are almost there...

but when you create each entry with different number (as c1::, c2:: ...), it means that they will be in separate cards. 
If you want them on the same card, use the same number. For instance:
c1::entering text, c1::second text ...

> Just a note, it won't work on the Preview (on Edit note) and on Edit Card type. But during the review it should work correctly
