### ISSUE TITLE
Duplicando texto

### ISSUE THREAD

**Issue by AntoninoStropp** [ssricardo/anki-plugins#54]
Opa, tudo bem? Falei com você no Anki. Olha, eu adicionei um add-on que me permite editar o texto do card da própria tela. Segue abaixo o link:

https://ankiweb.net/shared/info/1020366288

Isso demandou acrescentar o seguinte comando nas configurações dos cards: {{edit:cloze:Texto}}

Segue abaixo print de como ficou. 

O comando {{type:cloze:Texto}} eu já utilizava antes mesmo do seu add-on, com a diferença que não era "fill the blanks"

Achei seu recurso excepcional e essencial pro meu uso!

Por favor me diga se tem como resolver isso. Teria sido esse add-on (Edit Field During Review) que ocasionou isso?

Segue abaixo também o print de como fica o card ativando o seu add-on

![image](https://user-images.githubusercontent.com/61336831/75083234-6ae06400-54f6-11ea-9b0f-5d136ac009f6.png)

![image](https://user-images.githubusercontent.com/61336831/75083358-1c7f9500-54f7-11ea-8327-4c2acd47bc39.png)

**Comment by ssricardo** [comment]
Ah, entendi agora.

Não é o add-on que está duplicando o texto. Você está fazendo isso baseado em outro add-on.

Infelizmente atualmente não tem como fazer isso. são 2 add-ons completamente independentes. 

Acho que talvez seria mais o caso de pedir para o @kelciour tentar tratar type:cloze:Texto no add-on dele. Mas ainda assim, não sei se seria fácil fazer ambos funcionarem juntos. Sorry!

**Comment by AntoninoStropp** [comment]
Teria como, então, eu criar um outro tipo de nota para usar o seu addon sem influenciar nos demais cards "cloze"?

Porque em algumas situações o fill the blank não é necessário pra mim. Na foto do exemplo, trata-se de uma questão em que eu apenas omiti o termo "certo" ou "errado", que seria a resposta da questão. Nesse caso, seu addon não é necessário.

Porém em outras situações eu faço omissões no corpo do texto para completar um texto. Esse sim seria muito necessário pra mim.
Porém, ativando seu addon, ele influencia em todos os cards onde tem omissão de palavra...

Teria como resolver isso criando tipos de nota independente? Porque assim onde eu precisasse usar o fill the blank eu usaria um tipo de nota separado, entendeu? 

Eu abriria mão de editar na própria tela (o que é muito útil também), para usar o seu, entendeu?

Alguma ideia de como proceder? Agradeço desde já

**Comment by ssricardo** [comment]
Sim, também acho que um tipo de nota separado seja o modo mais fácil p/ contornar.

Você nem precisa de alteração em qualquer dos add-ons, já é possível fazer isso no Anki. 
Basta ir em Tools -> Manage Note Types -> Add

Depois você edita os templates, conforme quiser

**Comment by kelciour** [comment]
@ssricardo thank you for mentioning me, otherwise, I'd have no idea about it.

@AntoninoStropp I'm afraid, Edit Field During Review doesn't support clozes at the moment. You need to install Edit Field During Review (Cloze) by @BlueGreenMagick - https://ankiweb.net/shared/info/385888438 - to be able to edit cloze fields, if you didn't already do it, but I think you already did it and this is about Edit Field During Review (Cloze) and be able to use both add-ons at the same time.

Though I must admit I'm not sure how easy or difficult it'd be to add support to be able to use both add-ons at the same time, especially since some code might be changed after applying the recent changes in Anki 2.1.20 and upcoming Anki 2.1.21.

- https://anki.tenderapp.com/discussions/beta-testing/1708-anki-2120-beta
- https://github.com/ankitects/anki/pull/439
- https://github.com/ankitects/anki/pull/445

**Comment by AntoninoStropp** [comment]
Enfim, consegui resolver fazendo notas diferentes, sendo que um addon exclui o outro.
Agora, outra dúvida. No seu addon (fill the banks), o extra aparece como se fosse um outro "card"? Em uma segunda tela?

Pergunto isso para saber se fiz algo errado, pois agora o extra aparece em uma segunda tela, e não mais na mesma tela após o ENTER

**Comment by AntoninoStropp** [comment]
Thanks @kelciour 
Actually, I already had installed addon from @BlueGreenMagick. Sorry, I mentioned you inappropriately.

I did two differents type notes and I think it's enough for me. When I need "fill the blanks", I won't be able to edit it in the same field. But, no problem. Thank you for all

**Comment by AntoninoStropp** [comment]
Ricardo, agora que estou usando efetivamente o addon, surgiu outra dúvida também. Todos os audios que eu havia gravado da minha própria voz também não estão aparecendo no card. Procede ? Tem com resolver isso de alguma forma?

**Comment by AntoninoStropp** [comment]
Poxa, testei várias vezes aqui. Realmente no seu o audio some na hora da revisão :(
Não teria como consertar isso, por favor???

**Comment by BlueGreenMagick** [comment]
Is my help needed? I'm afraid I don't speak Spanish.

**Comment by ssricardo** [comment]
Hey thanks very much for the feedback @kelciour, even tough this particular thread is not in English.

Don't worry @BlueGreenMagick, Antonino wanted to use "Fill the blanks..." and "Edit Field..." on the same card. But for now he'll just it them separatedly (different note types). Thanks for checking it!

**Comment by ssricardo** [comment]
@AntoninoStropp 
Em relação ao áudio, veja https://github.com/ssricardo/anki-plugins/issues/45 .

Vou fechar a issue então, ok?!

**Comment by AntoninoStropp** [comment]
Olá. Vi na issue 45 que realmente o addon não tem suporte para áudio.

Você faria essa correção mediante uma contribuição ?

Se sim, me informa por favor, pois seria de grande valia pra mim

Abraços

Antonino Stropp

Em 25 de fev de 2020, à(s) 08:25, Ricardo <notifications@github.com> escreveu:

﻿

@AntoninoStropp<https://github.com/AntoninoStropp>
Em relação ao áudio, veja #45<https://github.com/ssricardo/anki-plugins/issues/45> .

Vou fechar a issue então, ok?!

**Comment by ssricardo** [comment]
@AntoninoStropp 
Então, infelizmente no momento me falta tempo mesmo. 

Além disso, não seria uma correção já que nao é algo que o Anki já tenha suporte. 
Aí como comentei no outro ticket, tenho que receio que precisaria de mudanças grandes no Anki, o que faria o Add-on mais incompatível com outros e  sensível a mudanças nas novas versões do Anki. 

Mas a ideia é boa. Realmente quanto eu tiver tempo, vou tentar analisar o impacto.

**Comment by AntoninoStropp** [comment]
Entendi
Tudo bem
Rpz eu enquadraria esse addon entre os melhores já desenvolvidos, na mesma categoria do image occlusion e do awesomeTTS, por exemplo

Sinto que realmente ele não tenha o áudio e vi que também não funciona no celular.

Espero que lhe sobre tempo, porque certamente inspiração não faltará! Esse addon tem muito potencial.

Parabéns demais vez
Obrigado pelo suporte
E abraços do Brasil !

Antonino Stropp

Em 26 de fev de 2020, à(s) 10:56, Ricardo <notifications@github.com> escreveu:

﻿

@AntoninoStropp<https://github.com/AntoninoStropp>
Então, infelizmente no momento me falta tempo mesmo.

Além disso, não seria uma correção já que nao é algo que o Anki já tenha suporte.
Aí como comentei no outro ticket, tenho que receio que precisaria de mudanças grandes no Anki, o que faria o Add-on mais incompatível com outros e sensível a mudanças nas novas versões do Anki.

Mas a ideia é boa. Realmente quanto eu tiver tempo, vou tentar analisar o impacto.
