### ISSUE TITLE
Fill in multiple blank - report isuue on incorrectly show the cloze

### ISSUE THREAD

**Issue by izanagiii** [ssricardo/anki-plugins#56]
Hi
Thanks for your contribution & efforts

I found an issue in the add-on, when the field content is not enclosed in a "\<div>\</div>" tag not only the content is not shown properly, but also the feedback doesn't work.

the demo of this issue is attached below as a .zip file:
[bandicam 2020-03-05 06-58-20-445_T1_C1.zip](https://github.com/ssricardo/anki-plugins/files/4291068/bandicam.2020-03-05.06-58-20-445_T1_C1.zip)

Thanks in advance

**Comment by ssricardo** [comment]
Hey! 
Thanks for reporting even with a video explaining it!

Which Anki version is that? That seems so different from mine...

**Comment by izanagiii** [comment]
Hi
Never mention it, You are the one doing the actual work

Anki ver: 2.1.20
UI: my custom note type for code snippet learning (if you like it I can send you the note type)

Thanks again, Looking forward to seeing your future update

**Comment by ssricardo** [comment]
I couldn't reproduce it yet.
For me, both Anki .20 and .21 are working fine. 

Maybe you can attach a small collection for testing...

**Comment by izanagiii** [comment]
Yes of course 

note that in the first card It asks about Word1 but shows all three of them as the answer, In the second card hides both Word 1&2 (should just hide Word2) & strangely the answer shows just Word2&3 (Word1 is not there)

Check it out yourself

The demo Deck is attachment:
[2020.03.13 - Test 2.zip](https://github.com/ssricardo/anki-plugins/files/4333185/2020.03.13.-.Test.2.zip)

Thanks again for the trouble

**Comment by izanagiii** [comment]
Hi
I found the problem:
It was a mistake from my part where a ">" sign was left out in my note template code

sorry for the trouble
Good luck
