### ISSUE TITLE
Could you please make version 1.7 available

### ISSUE THREAD

**Issue by yitzhakbg** [ssricardo/anki-plugins#57]
You have prepared version 1.7 in Github but not yet uploaded it to the Anki 2.1 addons.
Version 1.7 solves my problem with hints.
Kudus on this excellent addon and thank you in advance

**Comment by ssricardo** [comment]
Hi!

I'll do it soon. I'm just testing and adjusting for changes on new Anki .21

**Comment by ssricardo** [comment]
Just released!
