### ISSUE TITLE
Controller.wrapInitWeb compatibility issues with other addons

### ISSUE THREAD

**Issue by ccz-2** [ssricardo/anki-plugins#58]
Hi! Great addon - I just have some feedback after I was debugging why some other addons wouldn't play well with yours.
Essentially, if your addon executes before other addons which wrap **Reviewer**._initWeb (not mw.reviewer._initWeb), the other addons wrappers will not execute.
I realized it's because you overwrite the mw.reviewer._initWeb into a method of your Controller class  which wraps mw.reviewer in the state when Anki starts.
Therefore any changes to Reviewer._initWeb that are made after your addon runs not be executed when mw.reviewer._initWeb is called.
I figured out a workaround, but I realize it might be frustrating for other addon users/developers.
Happy to go into more detail - idk if my terminology is correct (I'm not an experienced developer)

**Comment by ssricardo** [comment]
Hey @Quip13 , thanks for all the details.
I'll take a look when I get the chance.

you mentioned a workaround, what is it?!

**Comment by ccz-2** [comment]
Great!

Here's the workaround that's now in Anking's button addon: [PR](https://github.com/AnKingMed/The-KING-of-Button-Add-ons/pull/3/commits/1c252d48d5d9dc7073a118d20540374d1b8eb708)

**Comment by ssricardo** [comment]
Hey!
Thanks for the reference. Basically that's the way it is currently. 
As it's not blocking your AnKing anymore, for now I think I'll just keep it... 
Otherwise other add-ons would make this one stop working also.
