### ISSUE TITLE
Doesn't work for Chinese.

### ISSUE THREAD

**Issue by EvanTsai370** [ssricardo/anki-plugins#59]
This add-on is really good. But the color doesn't change for Chinese. Could you update it to support Chinese please? Thank you very much!

**Comment by ssricardo** [comment]
Hey. Sure, it makes sense to add this support.
I'll keep it in mind for a future version

**Comment by EvanTsai370** [comment]
Thanks!

**Comment by ssricardo** [comment]
Hey @noamam , can you provide a couple of sample words?
Like 3 words, a correct beginning (is it right to left?) and a wrong case.

**Comment by ghost** [comment]
Great add-on! It works with chinese characters for me, but the problem i have is that the width of the box doesn't adjust correctly, it displays half of the lengh of the sentences. Any ideas?

**Comment by ssricardo** [comment]
Oh, so it works with chinese chars... 
@Vctorr could you provide a few words and their beginnings, so I could add some tests?!

Regarding the length, I'll make it configurable in future versions. For now, you can go to the addon folder, and edit the file _handler.py_ . Look up _0.62_ and increase this value.

**Comment by ghost** [comment]
![Capture](https://user-images.githubusercontent.com/62610920/77597072-043bd500-6efe-11ea-98de-55bf07a9bcd8.gif)

This is how it works for me. I'm not sure what you're asking, sorry. If it's the sentence i used, it's this one : 这是一个非常长的句子.

Also, edited the file and increased the value to 1. This is how it looks like now. It fits the chinese string, but the with latin alphabet it's too wide.

![Screenshot from 2020-03-26 01-00-10](https://user-images.githubusercontent.com/62610920/77597293-acea3480-6efe-11ea-9769-26ccfb09ef58.png)

**Comment by ssricardo** [comment]
Thanks very much @Vctorr for creating this, showing it working with those chars. 
And also for the sentence, that's what I needed. 

Regarding the sizing, indeed that's gonna happen; for roman alphabet, there will be remaining space... In the future I can try something different, maybe according to size of each character.

**Comment by ssricardo** [comment]
@noamam , as you can see on Vctoor's comment, it works with Chinese. Can you check your installation? Maybe updating the add-on or disabling other add-ons...

**Comment by EvanTsai370** [comment]
Sorry for getting back to you late. Here is my gif:
![2020-04-25-11-35-24](https://user-images.githubusercontent.com/22320280/80270400-20dc5000-86ea-11ea-9890-d1ade57250a8.gif)
When I type the answer, I need to move the cursor back to get the green color. And if I input the wrong Chinese answer, the color doesn't change to red util I move the cursor back again.
I guess it's because my Chinese input method is different from @Vctorr . When I type, it firstly show some English letter, which is called Pinyin, then I choose Chinese words that I want based on Pinyin. But @Vctorr is different, it shows Chinese words immediately.
So I think maybe the real reason is about the input method instead of the characters.  
My English is bad, sorry for some inaccurate expression.

**Comment by ssricardo** [comment]
This was added, at first as experimental feature.

Please update, and check the configurations.

Later, please provide a feedback
