### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by Uitalo** [ssricardo/anki-plugins#6]
is possible to modify this add for to work with pdf?

**Comment by ssricardo** [comment]
Hi.
Are you referring to the Anki-Web-Browser? (there are multiple addons on this repository)

It may be possible. I will take a look on that...

**Comment by Uitalo** [comment]
Yes, Anki-Web-Browser. Anki-Web-Browser

**Comment by ssricardo** [comment]
I'm afraid it's not possible.

Anki works only with: 
pics = ("jpg", "jpeg", "png", "tif", "tiff", "gif", "svg", "webp")
audio =  ("wav", "mp3", "ogg", "flac", "mp4", "swf", "mov", "mpeg", "mkv", "m4a", "3gp", "spx", "oga", "webm")
