### ISSUE TITLE
wikipedia search link

### ISSUE THREAD

**Issue by doulovetrees** [ssricardo/anki-plugins#63]
hi, 
for some reason when i paste this wikipedia search link "https://en.wikipedia.org/w/index.php?...{}" it does not search the term i highlight. it just pulls up the main wikipedia page.
i'm wondering what the issue is. i have tried deleting and reinstalling it but that didn't work.
maybe it is conflicting with an add on i have? 
these are the add on's i am using:

Advanced Browser
Anki Zoom
Browser Search Box Quick Insert Tag Deck Notetype
Browser Table Editor side by side
Clickable Tags
Create Filtered Deck from Browser
Custom background image and gear icon
Customize keyboard shortcuts
Customize sidebar
Edit Field During Review Cloze
Hierachial Tags
Highlight Search Results in Browser
Hint Hotkeys
Image Occlusion Enhanced
Learning Step and Review Interval Retention 
PopUp Beta
Rememorize Rescheduler 
Removes Empty Note Types
Review Heatmap
Special Fields
Symbols As You Type
True Retention by Maturity
Web Browser

**Comment by ssricardo** [comment]
@yhlai-code , I think the URL was correct. Here it worked with the following URL:

> https://en.wikipedia.org/wiki/{}

Can you check?!

**Comment by yhslai** [comment]
Uh? I never use Advanced Browser so I'm not sure why you tagged me.

But when I clicked the URL you pasted it looked like:

![image](https://user-images.githubusercontent.com/538696/78254947-39ad7780-7529-11ea-85b3-e112af4691da.png)

**Comment by doulovetrees** [comment]
figured it out. thanks! this is the correct link 
https://en.wikipedia.org/w/index.php?search={}
