### ISSUE TITLE
Doesn't work correctly with Japanese language 

### ISSUE THREAD

**Issue by EnzovdWetering** [ssricardo/anki-plugins#64]
Hi there,
I was hoping you can help me with the following issue:
It seems like the plugin only works with alphabet letters and not with Japanese hiragana, katakana or kanji writing.
Below you can see an example of what I mean. When I try to type the Japanese word for hello: こんにちは, I get no "live feedback" (yellow color) or "good" (green color) when typing the sentence. Only when I change the keyboard settings back from Japanese to Dutch, the plugin works. 

![Kapture 2020-04-05 at 14 10 00](https://user-images.githubusercontent.com/36194995/78485952-5921eb80-7747-11ea-8c49-514c233d70d8.gif)

My PC is running on macOS Catalina 10.15.3 and I'm using the Anki version 2.1.20 (47a1bf8b) with Python 3.8.0 Qt 5.13.1 PyQt 5.14.1.

I noticed that someone else already logged an issue for Chinese, but the issue I'm having seems to differ because he/she does get "live feedback" from your plugin.
https://github.com/ssricardo/anki-plugins/issues/59

Please let me know if you need more information and keep up the great work! 👍 

Your plugin has helped me alot with remembering long commands in IT-school, now I would love to use it to study Japanese :)  

With kind regards,
Enzo

**Comment by ssricardo** [comment]
Hey! 
Indeed I thought it be working, as somebody showed it working with Chinese.

But ok, I'll check this out with Japanese.  
Thanks for already providing a sample word. If possible, just tell 1 or 2 more words...

**Comment by EnzovdWetering** [comment]
Hi again :)

I've also tested it with these Japanese words:

今日 (today)
はじめまして (nice to meet you)
晩ご飯　(dinner)

I have the feeling that the issue is only present on macOS since Chinese seems to work fine on debian/linux (by the looks of the screen capture in case https://github.com/ssricardo/anki-plugins/issues/59)

Chinese and Japanese are actually similar in many ways. The Japanese 'borrowed' a lot of the characters in their Kanji writing scheme. 

Please let me know if you need more info :)

**Comment by EnzovdWetering** [comment]
Update:

I've just tested it on Windows 10 with Anki version 2.1.22 (0ecc189a) and Python 3.8.0 Qt 5.14.1 PyQt 5.14.1. As you can see in the screen capture below, the exact same behaviour occurs as in MacOS. When the keyboard settings are changed to Japanese, the addon does no longer function. When you switch the keyboard settings back to Dutch/Alfabet it works as expected and even gives you '(live) feedback'.

![Kapture 2020-04-06 at 20 27 06](https://user-images.githubusercontent.com/36194995/78593186-830e0780-7846-11ea-87e9-4cd7f48b9f0a.gif)

No other plugins were installed on Anki.

**Comment by ssricardo** [comment]
Thanks! I'll try to work on that soon!

**Comment by EnzovdWetering** [comment]
I have just tested it on Ubuntu 18.04, it does work there. So I guess it only does not work on MacOS and Windows.

**Comment by ssricardo** [comment]
Ok. 
When I work on it I can test on Ubuntu and Windows...

Do you have the option *feedback-ignore-accents* on? If so, can you test setting it to false please?!

**Comment by EnzovdWetering** [comment]
Hi there,

I didn't change the `feedback-ignore-accent` on MacOS, Windows and Ubuntu.
The default setting is configured: `feedback-ignore-accents": false,`

The only 'custom config' I have is the `feedback-ignore-case` which is set to `true`

Below are the settings I used for testing on all 3 operating systems:

```
{
    "feedback-enabled": true,
    "feedback-ignore-accents": false,
    "feedback-ignore-case": true
}
```
Please let me know if I can help in any way, I'm happy to do so :)

**Comment by ssricardo** [comment]
This was added, at first as experimental feature.

Please update, and check the configurations.

Later, please provide a feedback
