### ISSUE TITLE
How can it work on the content ended with " } "

### ISSUE THREAD

**Issue by s609078902** [ssricardo/anki-plugins#65]
hello

If a content end with "}", like "tags: { $size: 3 }", I don't konw how to let it work correctly. If I add a cloze to it directly, like "{{c1::tags": { $size: 3 }}}", it will show like this

![image](https://user-images.githubusercontent.com/48309185/78754187-a7362980-79a9-11ea-82f1-65ca1f212ade.png)

And if I add a space after "}", like "{{c1::tags": { $size: 3 } }}", my answer will contan a space and can't be matched correctly

![image](https://user-images.githubusercontent.com/48309185/78754594-55da6a00-79aa-11ea-8d42-47bba724833a.png)

Is there any solution to this?

Thank you

**Comment by ssricardo** [comment]
Hey! 
That's an interesting case. I'll check it when I work on next version

**Comment by s609078902** [comment]
> Hey!
> That's an interesting case. I'll check it when I work on next version

ok, thx!

**Comment by s609078902** [comment]
It seems that the problem has been solved in the latest verson of anki (or add-on).

Anyway, thanks for your useful add-on.

**Comment by ssricardo** [comment]
Hey! Thanks for the update and closing it :)
