### ISSUE TITLE
Changing font type and size and using for more than one field 

### ISSUE THREAD

**Issue by Fabioriz** [ssricardo/anki-plugins#66]
Hello!
First of all, thank you for having created this really useful add-on.
I would like to know if it's possible to change the font size of the words I'm typing into the blank fields.
And also, I have card with more than one field with close deletions. This code just works with the first field? 
Any ideas?
Thank you so much in advance!
Fábio

**Comment by ssricardo** [comment]
Hi @Fabioriz !

Do you know how to edit the style (CSS), on Anki?

Try adding (and changing) this:

```
input.st-incomplete {
    background-color: #FFFF77 !important;
    color: #333 !important;
}
input.st-error {
    background-color: #ff9999 !important;
    color: #333 !important;
}
input.st-ok {
    background-color: #99ff99 !important;
    color: #333 !important;
}
```

**Comment by Fabioriz** [comment]
Hello Ricardo!
First of all, thank you for reply!
Actually, after writing you I was able to find in a forum the code that changes the font and the font size of the words I'm typing in the blank fields.
The code I used is this:
`code#typeans { 
   font-family: "Verdana"; 
   font-size: 20px;}
#typeans { width: 150px; }
center { display:inline;
}
`
I noticed the code you sent me previously is inside the file "controller.py" from your addon. I've tried to include the code above in your file, but it didn't work.
So, the font size is solved!
The only problem that remains and I think there is no solution for it, is using cloze deletion for more than one field. 
Please, take a look at the pictures in the link.
https://1drv.ms/u/s!AnEpx-OEOT-biFibK6mK-fwuSpdh?e=gp0Wrr
https://1drv.ms/u/s!AnEpx-OEOT-biFfpZH-Arbr1lPGm?e=plJGTG
Thank you!
Fábio

**Comment by 3gatos** [comment]
Hi!  I am interested in this functionality as well, however, I am not clear where to put either code...
Can you provide code that can go into Cards>Styling Section?   I tried use both options provided above, and could not get it to work.   I'm not a developer, so would need some simple instructions if it can only be done in the source documents.  (edit:  specifically referring to the ability to increase the font size in the response fields, as well as change the font in the response fields as well).

**Comment by ssricardo** [comment]
@3gatos , you need exactly to put the changes on the Styling section of Cards.

You can try with that: `code#typeans { font-family: "Verdana"; font-size: 20px;}`

And use the number you want on *font-size*.

**Comment by ssricardo** [comment]
@Fabioriz , I couldn't access the links. 
What do you mean by more than 1 field with cloze deletion. Multiple fields on a single cloze?

> Sorry for the late reply, I don't have much time to work on these add-on lately :/

**Comment by Fabioriz** [comment]
Hello my friend!
Don't worry! I can imagine you have many things to do! Actually, it worked! Thank you!
About the fields, I was trying to say that on Anki, when you have a card with more than one field with cloze, this Add-on doesn't work.
For instance: Sentence 1 (first field), Sentence 2 (second field). Only for the field Sentence 1 youl'll have this Add-on working.
A think this is how Anki works and it's not something related to your code.
Thank you again!
All the best!

**Comment by ssricardo** [comment]
Fabio, 
but that sounds like something that the add-on actually does...

I created a sample deck, you can test with it: 
https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blanks---Starter-Deck

**Comment by Fabioriz** [comment]
Hi Ricardo! 
Thank you again for your interest in helping me!
I checked your sample and maybe I didn't make myself understood.
When I mentioned "field", I was not talking about a cloze deletion field, but an Anki field, as you can see in the follow screenshot. I mean, your cards have multiple cloze deletion fields, but just one Anki field.
Let me know if you got what I tried to explain.
Thank you so much again!
https://1drv.ms/u/s!AnEpx-OEOT-bizhW6iR8y-h_ga8C?e=bwxgpk
https://1drv.ms/u/s!AnEpx-OEOT-bizY5fzPyuxTi2f-V?e=fOcjzO

**Comment by BrucePlumb** [comment]
Unfortunately the Anki Manual says nothing about the ability to have multiple cloze fields, so many users are unaware of it. It is a very useful feature not only for creating overlapping clozes (no special add-ons required) but also for having different clozes all share the same Extra or Comments field.

**Comment by cyl55** [comment]
If anyone is looking for a way to change the size of the font inside the blank (text box), here is an alternative solution to the ones already listed.
Tools > Add-ons > View Files (for Fill in the Blank) > open controller.py
Inside input.ftb class, add attribute `font-size: 20px;`
You're done! Depending on what you use it to study, you may also need to fiddle with the width of the blank to accommodate the new size. (This wasn't an issue for my cards but should also be easily fixable inside controller.py)

**Comment by ssricardo** [comment]
Today's version added a new integration, which (hopefully) will also work for multiple fields.
Details: https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blanks-New-Integration
