### ISSUE TITLE
instant feedback doesn't work properly

### ISSUE THREAD

**Issue by izanagiii** [ssricardo/anki-plugins#69]
Hi

There is a strange problem with your add-on which I can't figure it out so I attach a video to explain it:
[bandicam 2020-03-26 07-26-41-864.zip](https://github.com/ssricardo/anki-plugins/files/4709543/bandicam.2020-03-26.07-26-41-864.zip)

description:
when I make cloze of a syntax (especially when copy it) after entering the answer feedback turns red although the answer is correct but when i manually type the whole cloze (with {{c1::}}) again the problem is solved

This problem doesn't happen all the time but it is common.

Thanks in advance for your time & contribution

**Comment by ssricardo** [comment]
Hey @izanagiii !

If you look at 00:00:17, the _dashes_ are different. The first one is larger. That means, it's not exactly the same character.

**Comment by izanagiii** [comment]
Hi

Yes you are right, I had not noticed it but now that you mentioned they seem different.
I wonder why they are different, but maybe it was an oversight due to changing keyboard from US-English to Canada-English keyboard (but I am not sure I will check it)

Thanks again for your time

**Comment by izanagiii** [comment]
Hi Ricardo 

Regarding this issue I checked another problematic card and it wasn't for the difference in dashes "-".

the Demo video:
[bandicam 2020-06-23 21-22-58-908.zip](https://github.com/ssricardo/anki-plugins/files/4820821/bandicam.2020-06-23.21-22-58-908.zip)

I am confused and have no idea since there is no html tag or styling involved so I can't see how the second one that I type manually is different from the first one.

Thanks for your time & patience

**Comment by ssricardo** [comment]
Hey @izanagiii, can you please paste here that line (the value which you had you the Code field)?!

**Comment by izanagiii** [comment]
Hi ssricardo
I found the culprit of this problem sometimes (normally when the text is formatted like color, ...) when i hit space it will use "\&nbsp;" instead of " " so if you can change the code in a way that it automatically changes "\&nbsp;" to normal space " " I think the problem is solved (but there may be a better way to do it)

**but** sometimes even after replacing "\&nbsp;" with " " the problem persist

here is the note file:
[Selected Notes.zip](https://github.com/ssricardo/anki-plugins/files/4957885/Selected.Notes.zip)

Thanks already for you time

**Comment by ssricardo** [comment]
The problem is due to mixing it with formatting tags. 
The add-on takes the text from the cloze entire area (until the _}}_). And it seems that there are spaces between the tags, and in the end (in the value used on the add-on), it expects multiple spaces. 
For instance on your card, it expects this: `ls  -la   /   ~/Desktop    /etc`

![2020-08-30_18-07](https://user-images.githubusercontent.com/28906929/91663854-aa15f000-eaeb-11ea-975f-27901a7c9dfa.png)


About handling _&nbsp;_ , I'm not planing to add additional handling to the value for now. I've tried that on other add-on and it causes many side effects, making it harder to maintain. Sorry...

**Comment by izanagiii** [comment]
Hi

Thanks for your time and trouble

Yes I understand that applying a fix is not just as easy, so I will stick to editing the html of the fields manually for now

Thanks again :)

**Comment by ssricardo** [comment]
Hey!
I'm so sorry, but currently I really don't have time to spend on this :/

**Comment by ssricardo** [comment]
In the new version, some additional handling was added for the values.
Hopefully it solved this, otherwise please open it again (maybe with some updated data).

> Addressed in version 2.7 (10.01.2023)
