### ISSUE TITLE
Include Major Mnemonic Support

### ISSUE THREAD

**Issue by dainius-sileika** [ssricardo/anki-plugins#7]
Hello,

Would it be possible to script returning results from this site?

http://numzi.com/numzi/index.cfm

Many of us who have numbers and dates to learn use the major mnemonic, and this is the best website for quick noun generation.

Thanks!

**Comment by ssricardo** [comment]
Hi!

Which addon are you referring to?
And how should it work? 
I didn't get the idea yet...
