### ISSUE TITLE
Does it not support some common Markdown syntax?

### ISSUE THREAD

**Issue by weidongzhou1994** [ssricardo/anki-plugins#73]
such as First line indent（\&emsp;\&emsp;）&  wrap（\<br\>）

**Comment by ssricardo** [comment]
Hi @weidongzhou1994 .
You mean the *Markdown Support*?! There are several add-ons here, then I'm not sure...

If so, it's based on https://python-markdown.github.io/, therefore it's supposed to support the same. 
But some additional processing is done, to make it work with Anki card. 
If I remember correctly, one of them is trimming the content. Therefore, it'd not work for First line indent.

**Comment by ssricardo** [comment]
Hi! 
I'm going to close this, as it's quite old and actually I'm deprecating the Markdown add-on. 
With current versions of Anki, it's seems it's not needed anymore.
