### ISSUE TITLE
Type-in-the-answer card blows away <hr id=answer> <br> formatting

### ISSUE THREAD

**Issue by SEE-ICT** [ssricardo/anki-plugins#74]
Details here:

https://forums.ankiweb.net/t/type-in-the-answer-card-blows-away-hr-id-answer-br-formatting/1622

Toggling this add-on creates/resolves this problem. Running Anki with all other add-ons enabled works fine.

**Comment by ssricardo** [comment]
Is it already solved?

I think you need to have an empty line the template.

**Comment by SEE-ICT** [comment]
Well, disabling the add-on solves the problem of an error being thrown, but I would like to keep using the add-on. I’m not sure what you mean when you say that the template needs to have an empty line. Where should that empty line be placed?

**Comment by ssricardo** [comment]
After the line with type:cloze:... 

But I'm not sure about that, I'm just remembering about some problem like this.

Can you post your Card Template?! Then I can try to reproduce it.

**Comment by SEE-ICT** [comment]
[Test.zip](https://github.com/ssricardo/anki-plugins/files/5078218/Test.zip)

This file contains a deck that triggers the problem when run with the add on enabled but not with the add on disabled. It also contains a video that shows the problem occurring on my system. Sorry to be slow to get it to you.

**Comment by ssricardo** [comment]
Thanks for providing it. 
Lately I'm also late to reply, I don't have much time to work with this now; 
but verify it as soon as possible...

**Comment by ssricardo** [comment]
You are tying to use the add-on on the wrong note type. 
It works on **cloze deletion** notes, not on Basic (or Basic / reverse). 
Besides, on the card template it must contain {{type:cloze:Field}}. 

Please, review the documentation: https://github.com/ssricardo/anki-plugins/tree/master/fill-the-blanks

And I also created a starter deck: https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blanks---Starter-Deck
