### ISSUE TITLE
Ignoring Case

### ISSUE THREAD

**Issue by mattjukes** [ssricardo/anki-plugins#75]
Hi, I tried to add your conditional for removing case, but it doesn't seem to work. I think i've added it wrong. Could you tell me how I should apply it please?

```
{{Question}}
<br>
<br>
<span class="content">
<amd trim="false" feedback-ignore-case="true" replace-spaces="true">
{{type:cloze:Text}}
</amd>
</span>
```

**Comment by ssricardo** [comment]
Hi @mattjukes  !
I'm not sure, what you're trying to do. 

The `amd` is for the Markdown addon. But there is no feedback on that Addon.

Maybe with you want the feed on the other addon, the *Fill the blanks*?! 
If so, you should go to Addons -> config.

Let me know...

**Comment by mattjukes** [comment]
Hi, I didn't know the _amd_ was for another addon, I copied it from the examples in the _Fill the Blanks_ addon, so I have no way of knowing.

However, thank you so much, I had no idea that addons have a Config section, so I apologise for my mistake, but thank you for pointing that out.
