### ISSUE TITLE
Type-in-the-answer card blows away <hr id=answer> <br> formatting

### ISSUE THREAD

**Issue by SEE-ICT** [ssricardo/anki-plugins#76]
Sorry to reopen this, but I think that the issue is not resolved. The problem is not that this add on is not working properly with the cloze cards for which it is intended. I have in fact not yet tried it in that context.

The problem is that this add on blows away the formatting of _normal_ (i.e., non-cloze cards) type-in-the-answer cards when it is enabled. Since I would like to use both normal and cloze type-in-the-answer cards, this is awkward.

**Comment by ssricardo** [comment]
So I'm afraid I'm not understanding the problem.
On the video you sent, which of those cards have a problem? And what should happen instead?

The only part I thought it could be, is the wrong formatting on the `Test 3 Test 3 Back`. 
But on my Anki, it's shown (even with the add-on enabled) like this:

![2020-08-30_17-41](https://user-images.githubusercontent.com/28906929/91663356-90bf7480-eae8-11ea-8845-4e1cf724428a.png)

**Comment by SEE-ICT** [comment]
Works for me now, too. No idea why it failed to work before and works now. The problem was certainly reproducible, at least for me. Today, I deleted some add-ons. Maybe one of those was causing the problem. If I encounter the problem again, I will let you know.
