### ISSUE TITLE
Blank front for {{type:cloze:Text}}

### ISSUE THREAD

**Issue by cati-chatou** [ssricardo/anki-plugins#78]
Hi. I have an issue, but I might be doing something wrong, if so, could you help me understand how to configure this?
Front template:
{{type:cloze:Text}}

Card:
駅の{{c1::ちかく::近く}}にスーパーがあります。

Result: front with an input field only, empty otherwise. Is this because of Japanese?

I am using Mac, Anki Version 2.1.35 (84dcaa86)
Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

**Comment by ssricardo** [comment]
Hi! 

It could be something with the Japanese characters, but I'm not sure; There are people using with that.

Can you download and try testing with the follow starter Deck?!

https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blanks---Starter-Deck

**Comment by ssricardo** [comment]
Hi @sanjiro-san . Any new on this? 
Do you still have a problem?! 
Otherwise I'll start closing some old issues...

**Comment by cati-chatou** [comment]
Hi @ssricardo. Thanks for reminding me that I didn't answer, apologies for that. 
I reinstalled the plugin and it works beautifully. :) 
Thanks so much!
