### ISSUE TITLE
empty cards on the iOS mobile App

### ISSUE THREAD

**Issue by NiciUchiha** [ssricardo/anki-plugins#79]
Hello,

i have a problem with your plugin, on the desktop version everything is working well, but in the iOS App my cards are empty, there is just a "enter answer" button but no gaps etc. 

How can i fix this?

**Comment by ssricardo** [comment]
Hi!

Any Anki add-on is only for the Desktop version. 
So far, there aren't add-on for the mobile ones. So it behaves like Anki's default way.

Unfortunately, there's nothing that I can do.
