### ISSUE TITLE
Import Image Imports Code

### ISSUE THREAD

**Issue by dainius-sileika** [ssricardo/anki-plugins#8]
Hello,

Often, when I right click and assign an image to a field, I get code instead of an image. For example:

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUSExIWFRUWGBYWFxgXGBYYFhgXGBYXGBcXFhYYIiggGB4lHRUZIzEiJSkrLi4wFx8zODMtOCguLisBCgoKDg0OFw8PFy4dHR0tLS0tLS0tLS8tLS0tLS0tLS0tLTctMC0rLS0tLS0tLS0tLSstLS0tLSsrLSstLS0rLf/AABEIAQUAwQMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAAABQMEBgECB//EAEgQAAECAwMGCggEBgECBwAAAAECEQADIQQSMQUTIkFRkgYUFTJSU2GR0dIjM0JxcoGhomJjk7IWQ1SjseEkgvAHNHOzwdPx/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAECAwX/xAAkEQEAAgECBAcAAAAAAAAAAAAAARECA1ESMXHBBAUhIjJCYf/aAAwDAQACEQMRAD8A+4wQQQBHAoQuytlMSxdTVZ+nafCE8lU+SrOKSpjzn1+/YY8rxPmuno6vBGM5RHymPr1dsNGcovlt+tVBENktKZiQpJp9QdhiaPTwzxzxjLGbiXKYr0kQQQmynxnOHNKITcDMZV0KdV4rCwVa0NdpQv26Q5ghHYZNqTMQV2gqlvOKgoSXLTCJABQkMChbnW8tNQ6r0OTpduMyWZs1pYSc4GlG/M0KIKQ4l866+lje1MGigjMPlC/RQKROK3UZSb0m82aSEpPsqJCiUkqQHIFFAmW9RlKcpSBIEwHi+koKXn1Eh7qSLhpWjAByQGngjJ2XlLMspTzCAyjmAxSEFRUEuGJEwBnxD3dV/Jkq1iYjOzwpAEy+AJekQppTEAEApWSQzhUpIBZ74PYI5eG2OXxg4gPUEcChtjgWNogPUEeQsbRHqAIIIIAggggE10dL6wRVaCA0cUspWqYgeikGcs6ryUJHapav/gE9kXYIDA27K+UpKs5MyTLWkFyZUy+v30BV87sWck/+I1gtHo5pMhWBE4C5THT5o/6mhpbMvoQFaSwoKCSGTT0iUudEsSklQ2h2illdWT7QpQtFnSq6kaZSy+etJS6WUnmA41vD59MdPSqYnTq9u+7Nzu0tkTKa9LuMdaWYj3iJ5cwKDpII2guO8RjMj8EMk50iXZgVpAURMMxYa8QlV1ZKS5Spn6J2RtAGoIxwYYe3CKjpS3M83YRZZ4OJtExSyoC8gI5ulRM1I0nButOU4DVAqNb2EOXskWicsqlT1ShcCaLWHOcSp7ooKJIvCrKI7RFV53BBCi98PoMLqrgUAErUGWF6SUSgdP8AlDaXsL4OO16YCEqmlOhUCbNE1TEkssKAurGAJoTUXsn2NaFKKphUCVFIJUWvKKi7n4QBqYgQwgMsOA8gZopUpObzZOvOGWUKBVedtKVLUwZjLHbHbFwNlozXpD6IIQwBurQm9ozErKncqSXDNcDMCQdRHDAZ+1cFUKlyZYmFAkSzLRdShtJIStRBFCUgijc5W2OnglISb0sXFC5cJK1BJRNM0kgq0nUS+tjQiI5WRbTfCjPLBUp2mTS4SBfVdNApWkGe6yxR0aVrJ2SJksyyqcpVxEpCnXMVfuS1pUo3iXKlKSSTXQGsmAhVwZBvvMDzAsKUJabwziphVm1Ke4GnKDV1drxq4ISiGvl7iZd4JQFXECelIoGLJngYN6MUjSQQGesfBVEuem0BZvguUpSEy1aM4ABNboBtCiKvVVTeMQngZKEtMpKyEiUmUSReVohekhROhevm8MCABQY6eCAzUngdKTNTNC1aCgoBhW7NXMReOKrudmJHYsu5rGlgggCCCCAIIIIDOQQQQGjgiC3+qmfAr9phYrg5LK1KMyZpKvXQq6kVGikJAYMAG95xJMA3zSeiO4ay5+sczKeiO4bX/wA1hNM4NJIPpZge7UFI5qQKUo7Odpfa0Wsn5FlygQSZjl3mMo4JFKMOa9BiTAMEykglQFSACewOQPuPfHuEVr4MoX/Omo+BQD1J2awW7mZhHk8FkOPTTqABrwqwNTR3JJPdqAEA/iharAtS76Z8xGGiLpSwxBSoEV240itauD8tYYLWjVoEA+zrILnQxPSVtiJXBlBQpGdmgqwUFC8nTCtEkHY1XoSMKQFtFgnAEG1LJISHKJdCDUsE4nujycmTdEm0zCUknBICqJooJZw6SdukYqSOC6UzBMz85TF7ilJKKly6WD17hQMIccTl9WjdTAUuS1uDxibQpLPQ3S909itf0uikdXktZxnzBRtEkeytL0NTpA+9Ii5xOX1aN1MHE5fVo3UwFFGSlhYVxmawUDdfRYKKm7ix7AMIDkyaXe1TC4VgEJYlJAIKQDR3DnUIsWzJctaFIACCRzkBIUO0FoWTeCySQoT5wYpNFJY3dSklLFxi+ONDAW5OTJoI/wCVMIBBYhFWLkFTOQaj3YNHZuS5igAbVNBBJcXQWIDBgAKM9QcTFWwcGESpl/PTZgYC5MUFJYBhRqnWSXJNYb8Tl9WjdTAUlZMmkMbXMfSqEyxRQTRglqXSQcdI1hlLSQACXIAc7e2IuJy+rRupg4nL6tG6mAngiDicvq0bqYOJy+rRupgJ4Ig4nL6tG6mDicvq0bqYCeCKVtscvNr9Gjmq9kbDF2AzkEEEA8t/qpnwK/aYWzsnWit2f7RIcrom9RONaNXsOLgpZW/1S/gV+0wptnCRMtRSqWSRe5omK5nO5qD3Ylw2IcJZVgtAUSZt5N0gAmYCFalEg6QejUpFfky2MBxkOzE6dTSt16Psem06vSOEqSCoILBN/wDmGjtQBDk9jPHgcKUXrtwvTVMAqoJ5xQ2JGuAmRk+0ukmcCKOHmVqt6vRwUbphpxVO1e/M8YXWjLgQSFIFCASCshym+BRD4EamrHFcIEBnu1AUPW4HD+Xj2Y9kAy4qnav9SZ4wcVTtX+pM8YXSsvJUUpADr5vra6Sk9XSqTjqYxGeEsoa07f5zbcc32wDXiqdq/wBSZ4wcVTtX+pM8YU/xLLZ21PhO/wDraGUi0LWlK0pQygFDTVgQ49iAk4qnav8AUmeMHFU7V/qTPGC9M6CN8+WC9M6CN8+WAOKp2r/UmeMHFU7V/qTPGC9M6CN8+WC9M6CN8+WAOKp2r/UmeMHFU7V/qTPGC9M6CN8+WC9M6CN8+WAOKp2r/UmeMHFU7V/qTPGC9M6CN8+WC9M6CN8+WAOKp2r/AFJnjBxVO1f6kzxgvTOgjfPljwm0LJIAlkjECYSR7xdpAe+Kp2r/AFJnjBxVO1f6kzxjmcmdFG+ryR2/M6CN9XkgIbbZU5tdV81XtzNh7YuxStqpmbXoI5qvbOw/hi7AZyCCCAeW/wBUv4FftMU7Rl6zoouaEY86mDvjsY9xi5bvVr+BX7TEczJshRvKkyydKpQknSa9UjWwfawgIE5ds5dpgLAqPwihPujqcuSDgsHDCuJAHeVDvETSsmyE0TJlpYNRCRTFqDDsjqsnSS5MqWXd9BNXIJemspSf+kbICDlqRdEy+LiuarUo3b1Dr0QT7hHBl6z4ZwP4lh9aROcmSCLpky7ru1xLPtZsaQJyXIGEmWNfMTiC4OG2sB5s2VZUzmKv4HRBNDgabYmNoHRVuqgs9ilIJKJaEk0JSkAkOTVu1RPzMTwEPGR0V7qo4LQOirdVE8EBDxkdFe6qDjI6K91UTQQEPGR0V7qoOMjor3VRNBAQ8ZHRXuqg4yOivdVE0EBDxkdFe6qDjI6K91UTQQEPGR0V7qorz0S1gpVLUQcQUqbG9/kPF6KkywghTKUkqxUm6Fc58W+VdUBUOTrNT0BoEpGiqgSAEj3ACLNkRLlC7LllIJcgIVUnEntpHhWSySDn51ABzwHYByWTiWc/OLNks9wNfWurusgn3UApAQ220DNr0Vc1Xsq2GLsQW31a/hV/gxPAZyCCCAeW/wBVM+BX7TCm2ZMtRV6O0BCdLETFH8HtCg1irtiHYNcon0Uz4F/tMJeUp3T+1MBLJyZam0rQHutS/wA5+cATg1G+sEzJlrq1oTjRxMNNYa9j2vTYdUPKc7p/aIOU53T+0QE4ybaryTnxduAKHpHMy8XWFXuaxGi2rEO4aCyjWVfqTPGEnKc7p/aIOU53T+0QDC0WRRUoS1qSbqDVcwipW9H7B72amIoS8l20GtqSoMaNMSbz0Y3jQBxhWmEVpmWVJUSZrFgDohg15WylCT7g8Ry+FAIChPSUliFMLpcKIYsx5iu4wDWZk20sGnh6O99jzrxGlR3SdbXdbwS8nWkLczwUMjR9IC4Avuq9UEgsGDPiWYrZvCIpBKpt0AsXQzFgWLjYR3iPI4TVu54Xtl2p9wav+xAafiqdq/1JnjEVqswCFkFbhKv5kzYe2M6OEwIcT0kO1AMWUWNKUQrujzN4RAhSTOFNFWiHBINMMWB9zQDW2ZNtJU8u0BCdhvqLNtvU+uHaw8ysm2ttK0Am6oUzgF4p0SAVFgFanL7YXfxNUjPDRN06OBAJIJalAe6OS+E4VhPSaE80MyQSS7agD3QF/ky2Of8AkJa8SkNMe6SCATexFQ7VfCHCLKGqVP2TJnjGYRwoBdp6SwBLAMAQS5LUoCexjHEcKUkgC0JJOAYPUpTg21aR84DU8VTtX+pM8YOKp2r/AFJnjGWXwpAF5U9IFKkAc6qRUYkYDXFxeVZoDlf2jwgHpsidq/1JnjBxVO1f6kzxhCMrzOsGD4JwxeAZXmHCYnuTtb/IgH3FU7V/qTPGDiqdq/1JnjCPlOd0/tEHKc7p/aIBtbbKnNrqvmq9uZsPbF2MvbMpTc2vT9lXsjYY1EBnIIIIB3lAeimfAr9pjH221rl3v+PPXdUU6EtSnYgOnaC5IOxJ1sDsbf6pfwK/aYW2nhLZ5arqyUnToSl9B77VqzH/ALMBTsdhmTE3gLtSGW4NCRg3ZE/I8zajvPhDGy5QExIWhClJOBBRViR0toMTZ9XVL75fmgFHI8zajvPhByPM2o7z4Q3z6uqX3y/NBn1dUvvl+aARzODxUXUJZ95Pu2bCR7qREOCqWbNyWxZqOVFRLXdqifmdsaHPq6pffL80GfV1S++X5oBErg4SGKZZd8XOKbpNR0ae6PJ4MOXKJRLu5cl61dnepr2w/wA+rql98vzQZ9XVL75fmgEKODIDsiUHx7aEV0diiPmY8TOD1wKUESnAKjjUgKxN2tFK3jtjQ59XVL75fmiG2T1Ztfo181WuXsP4oDLryYELKOL6xpBLpUSEi84Dn1pqdi4glWVNALIsAggG5oh0OofhDTCDgHvbDGnn5fkoVdU4VUNou4uOKGvrE9/vi8LQrq198vzQGOyZk5M0rQLMZTGucllAU1HFNKivqe0R4kZNlqnFAsrG8UZwy2QSAp7q2c0B1a9rttM+rql98vzQrs2TSiaqa9pJWq8UqmIKBQgBKb2iGIoNYBgKU3gqlQKVS5KgQxBDghrrEXa0p7jFpWRphxKO9XhDfPq6pffL80GfV1S++X5oBErg4SXKZZLXXcvdYhsNhPfHgcFk9XK268Qzez2DuGyNBn1dUvvl+aDPq6pffL80Ao5HmbUd58IOR5m1HefCG+fV1S++X5oM+rql98vzQCO2ZImZtdUc1Ws7D2Ro4pW2erNr9Evmq1y9h/FF2AzkEEEA8t59FM+BX7TFTjtmd3S+L3C7+9ot271a/gV+0xRncHrOoklBdSis6SxpEu9D2nvgJJWULMnmlKfckj/AiTlWT0/orwiv/D9nvX7hvXgt7y+cCog47VHviGZwUsijeMovevc+Zzq153ae8wF7laT0/orwg5Vk9P6K8ImsdlTKQEIDJSGAcmnvMTwFLlWT0/orwg5Vk9P6K8IuwQFLlWT0/orwg5Vk9P6K8IuwQFLlWT0/orwiG2ZVk5ten7KtSth7IZxDbfVr+FX+DAVFW+znEg+9J8O2PYyrIHt/RXhEFp4PWeYpS1oJUqpN5YegGAOwQL4P2ckkoJKiSdJdSVXnx6VYCxytJ6f0V4QcrSen9FeEVJvBqzKCUmWWSzaaw11S1BmO2YqmwthSLOT8kSpJJlpIdndSlOztzidp74D1yrJ6f0V4Qcqyen9FeEXYIClyrJ6f0V4Qcqyen9FeEXYIClyrJ6f0V4Qcqyen9FeEXYIBZbcqyc2vT9lWpWw9kM4htvq1/Cr/AAYmgM5BBBAPLf6qZ8Cv2mFc3g+5JE1QdRUAAlhsT8NcOwfNpb/VTPgV+0wltarcl7gUvSIxkJ0QcajWKt79lQm/h/SvZ1TXgq6AGoSbtfZLsR2Bmjv8Phwc4qhBIpXScjsDU+Z7Gp53KFNA1KQdORQF3VhVqU7T7oknKt4UyQpQppXpAxQ5oQ7BWj3H3BYlZAAC051RC0s5CbyaBLoV7JYPV6knXEaeDlQTPXiDglixJYjYXq2yjYQTBbXUxJASspJMkXlDmJa7R9pw/wAxJVlDAit5nvSrt1+e918NTP3VC1ZsghKkqMwqus4KUspk3S/vx98MuJy+rRuphEheUCC6SCwLXpNTcUohwC2kEpf8T4CGqLLOatoU/wAMvywFjicvq0bqYOJy+rRupiHik3+oVuS/LBxSb/UK3JflgJuJy+rRupgNildWjdTEPFJv9Qrcl+WDik3+oVuS/LATcTl9WjdTBxOX1aN1MQ8Um/1CtyX5YOKTf6hW5L8sBNxOX1aN1MQ2ixy3R6NHO6Keirsg4pN/qFbkvyx4XYZhZ7QqhfmS9hHR7YChNyCk3fTqSzOBd0qMxdyxZ6MXJ1MBJLyKgKLzSp1BQBu0uqSopDNQgMXfHU5eJXBWWQQVqILAuxdkZsO+OhSBPBWWE3L5u3Fy2ISRcWAFpY6iEiAsWHIqUKKjMMwEmiwggOQWDAYYDWx1wx4nL6tG6mF1hyFmQEy5qkgAAUSaDDnA/wDZMW+KTf6hW5L8sBNxOX1aN1MHE5fVo3UxDxSb/UK3Jflg4pN/qFbkvywBbbHLza/Ro5qvZGwxdhZbbLNza/8AkK5qvYl7D+GGcBnIIIIB5b/VL+BX7TCyZl0pJBkKoSmjl2WEONGuL7Wq2Ds7d6tfwK/wYngEaMvKKggWaY5ZsWqH5zNTXsjz/ERdA4tN01IRzVG6VsxWyTdTUOrAV2Fn0EAnTllZws6/Z2+0VDZqu12PWI5eX1KqLNMweoIYM9XFPn4w8ggEkvLxKgnMLS5Z1XgkHQa8btHC/sV2OzC5nQRvnyxYggIL0zoI3z5YL0zoI3z5YnggIL0zoI3z5YL0zoI3z5YnggIL0zoI3z5YL0zoI3z5YnggIL0zoI3z5Y8TZ0xIe4jFI559pQHQ7YtRBbOaPjl/+4mAUHhEWfi8zB2Yk4KVspRB+bDEgRKvLigQBIUp35rlmKhWlOa/uKdohjYLQZiAsoUgl9FQZQYkV7n+cWIDOy+E5UkKFmnVehSoKo9SCNEFqO2qLVpyypDvIUWBOiScEhTCna3yOqsOIIClZbVMWm8JYTVQZSiDoqIdruBZx2RNemdBG+fLE8EBStqpmbXoI5qvbOw/hi7EFt9Wv4Vf4MTwGcggggHeUD6KZ8Cv2mE3K0/bL3FeeHOUB6KZ8C/2mE/JM78veV5IDnK8/bL3FeeDleftl7ivPByTO/L3leSO8kTvy95XlgOcrz9svcV54OV5+2XuK88d5Infl7yvLByRO/L3leSA5yvP2y9xXng5Xn7Ze4rzx3kmd+XvK8kHJE78veV5YDnK0/bL3FeeIFcIljFcrFuYvFylufi6SANbHZFjkid+XvK8sQHg4o1uSsX568XJcaNC5J7CTtMB4PCZQLZyU7lPMXzhQp52PZjUR5TwpJBUJsggEgkJUQGd306YGPY4Mnq5IreopQ0i2lzcaCuNBHBwXoQJUkA1IBIBo1dCtIDkzhQUtemSg+DoWNT61bK9kH8UF2zkl64oWGZnd10Zw+y8NoiSZwcUrnS5JwNScQCB7GoExwcG1D+XJxc6SnJ2k3a4QBI4RLWWSuSSwUwQp2IBB5+xQ74km5TnKDPLxSeYrUQen2RFJ4MlBvIlyknBwpQJHaQmvzizyRO/L3leSA5ytP2y9xXng5Xn7Ze4rzx3kid+XvK8sHJE78veV5YDnK8/bL3FeeDleftl7ivPHeSJ35e8rywckTvy95XlgOcrz9svcV54OV5+2XuK88d5Infl7yvLByRO/L3leWAgtmVp+bXWXzVewrYfxxp4zNsyTOza/V81XtK2H8MaaAzkEEEA8t/qpnwK/aYWryXLKlLuzgVG8bswpq4NLqg3N+phlbz6KZ8Cv2mFc2ckmluQlOnQGW+leu6RL6N4N8IgAZIlApVcn3ki6DnC7FRUb2lpVJqa1pDQTj0F/b4wvydakS0su2ImnUVGUk4a7tD/ALi5ynI66Xvp8YCXPnq1/b4xSyhZETrpWiY6SSClQSQ/aD2RY5TkddL30+MVLdapaykotiJd0l2VLN59oUWgPVlsSULvhM4mo0l3wAogkAKUWwGGyL2fPVr+3xhKFl35RRq1SdTf5Y98NE5TkdfL30eMBNnz1a/t8YM+erX9vjEXKcjrpe+nxiK02+SpCki0S0kggKC0OkkMFCuIxgLWfPVr+3xgz56tf2+MKrNOSlTm3IUgPokynYl6rxJEMOU5HXS99PjAS589Wv7fGDPnq1/b4xFynI66Xvp8YOU5HXS99PjAUrVkyWtSllE4FRSo3V3QSkJCSwVquiPdksSZa74TOKiGN5d5xjgVdp7ztiC1TUqUoot6UAkEJeUoBmoHLsSC+292R2xzwlQK7eiYK6JzKXdmqmtGPfANc+erX9vjBnz1a/t8Yi5TkddL30+MHKcjrpe+nxgJc+erX9vjBnz1a/t8YpW22SlgXbUhBBJcLQX0VAOCagEgt+ERDYLSlBN+2omjU5lBqk4g1xA+UAzz56tf2+MGfPVr+3xiLlOR10vfT4wcpyOul76fGA822ec2vQVzVdHYe2LsLrblORm1+ml81Xtp2HthjAZyCCCAd5R9VM+Bf7TGdzK+gvcX4RosoH0Uz4FftMZy02uaSoy509F4uxRIWACRQOpwwBAripy9BAdzK+gvcX4QZlfQXuL8I8qtU1iM/aKl+ZZthDY0xB/6e0x746tqzZ5N4KBuyAwAVTRUHdwavzRAczK+gvcX4QZlfQXuL8InyflNSHvqnzXbnJkJY6yLqhj/APjRd5dT1Uz+354BXmV9Be4vwgzK+gvcX4Qxl5bSAxlzTjU5vWX6ce+XU9VM/t+eAV5lfQXuL8IMyvoL3F+ETWzKN9aVAz0BLOlObYsoGunrFO7tBmsOVQhN0pnLNHKjLJcADp0wf3kwCS02G1lRKVKSliwzajVg3s0YvrLvqjsqxWoKqVFLq9hQoeaGu4iuur9kaHl9HVTP7fng5eR1Uz+354DNSLDbQtJUolNLwzanPOdiEjanujzLsFtExKismWzKRm1AuzXgq7rJJb3Da7RdtmF7s6elyo0RZ1M5J9tSsHAA/DDJOXkgVlzD2+i88Aps1nmhCQtK1KbSNxQc62AFBEmZX0F7i/CGZy+jqpn9vzx3l5PVTP7fngFeZX0F7i/CDMr6C9xfhDTl1PVTP7fnhWq1LvqUmdaUhSgbt2zqCQLzpTeJYFxujtcDMr6C9xfhBmV9Be4vwi/ZcshKEpUiasgAFREoE9pAXEvLqeqmf2/PAK8yvoL3F+EGZX0F7i/CGnLqeqmf2/PBy6nqpn9vzwCi0SV3VaC8D7CtnujWwkteW0lCxmplUqH8vYfxQ7gM5BBBAO8oD0Uz4F/tMIV2ViQZskEYgzKj30h/b/VTPgV+0wltsqWSSuzzVkKUl8zIWTzXUNF2L/O6YCsEoNRPs5rd9aMcGwx7I98W152T+p2kbNoI+Rj2iRJICuLTRR2MiTexCWa7i1fcIkn2OUGBkLVz0gCTIIAQ6taaAklu0wEVnsRmPcmSltjdWVNiNQ7D3RNyPN/BvK8seZM1MohCJNpSGFUSZbU1EgV/3HpOVlsCZNsDu4zUpwBrLUrAHI838G8rywcjzfwbyvLE5tymJu2rAFs3LeurDERHIymVKKQi1BsSqXLABukthjQD5iAUz+BQWSS1SonTPtKKj7G0mOWjgSFm8sgmpe+Ri781A6R72whsnKaze9Ha6B6y5YeoDBxjpP8AI7I6vKpAe5a6JvH0UtxpKDM2Oi7bCNsArXwNdnI0cDfOpRUKXGoVbOza4OBxpUaJQRpmlwkpqEPrI7QWMNU5SUS2btevGVLAoHxb5e+PJyop/V2zXXNS9XygFy+CJOsNoUvHFBUUHmOSCp6vUB3iGVwGSkgjUGHpFNgRhd2U9wAwAEO5tvUH0LUWbCXKLuCS1NTY9oiIZXLPm7XtHopbkUqA3aIBb/B3N5pugAaZoApKm5lXKEuTU3RWCRwNuLRMDXkPd01MxCgxF2vONTXDZGkst5aQq/NS+paZYUPeLtIlzCutX3S/LAJ+R5v4N5Xlg5Hm/g3leWHGYV1q+6X5YMwrrV90vywCfkeb+DeV5YOR5v4N5Xli7lGcqUEn08y8oJaWmWopoTeUCBohtW0R6sExU1F550v8MxMtKu67AUOR5v4N5Xlg5Hm/g3leWHGYV1q+6X5YMwrrV90vywCO05JmhCjoUSr2lbD+GNHFK2yVZtfpF81WpGw/hi7AZyCCCAeW/wBVM+BX7TC+fbVJd02ksopdMuWp2u6QADsb1PhMMLal5awzulVMXodUKJyJlbkuTzjdvSZo0aXXZNTzvpASIyiTdNy1C8FGspFLoUWULrgm7TaSBriNWVldVbCf/RR/kho8JTO0XlyMFXgJM7FjdulsHuu+p4jUi0apdmGFcxPPvowgLUrKalKAuWsOQlzKQBUs5LUA1mOHKhABKLXg7ZlLjSUliycdF/cpJ1xDLTPvVl2e7ou0mc+Ok2jswguzmHorOS1fQzgHvK/Dhdu/O92QEyMqEoC7lqYkADNIvMQTeYDBk/UDXHUZSUbuhaw5aspFObzqYaWPYdkV5SZ9zSlSAtwWEmddAYuObi7VwxpAlE+jy7Piq96CdzdG6xah5z/KAnVlUj+XbCzCklGtuyuOrZHpeUSGN21VANJSHqQwZner9jF4rNPp6Kztr9DOp9tYEpntWVZ3dP8AJns2lerd+FvnAWU5SLgXLXUgPmkMHap0e3/OyBWUlBN7N2vFmEqWTgTswpjhUCIJSZz6UuzsysJM53bRxGD4wKTOakqzktrkzhWn4cMfpAT8olnu2rnBPqkvUKL83AXWJ2kbY5ymXa5a9nqkN/iK8tM9xelWcB0uBJnPdpeY3ccW+UekInOl5chm0gJE5wb1bpaou7dcB7GVlEtmrZrrmUNT5a4kmZSIpdtRLqFJSPZCTeGjgb1O0ERWuz+qs36M/DdjqxOvUk2e7TGVOfW+CfdATpymq9czdrxAfNIu1LO7YB3PZDTMK61fdL8sJFInNSXZwbvUziL1/ZdFLnzc7IFCfqlWcYYyZx9+CYBnbclpmgCYpSgC45gIN0pcEJcFlEONpivZeD0qWoLQVhQw0nAx1ENrivZUzb/pJUi5XmyZ17sxS0Mbsnqv7KvLAT5hXWr7pflgzCutX3S/LEF2T1X9lXlguyeq/tK8sB22yVZtfpF81WpGw/hi7Cy1IlFCgJVbqm9ErFi3swzgM5BBBAaOKeVLWmWgKUu5pJD3Sp6glLAHFIIfU7xcggMsrK601VakMyQWs01nZRJd9Yan4e1o8TcqzghZFqQSkXv/ACs5Ia8AB7RD30DWecRSg1kEBlpmVpjAi03cEK/4yyL7lV9IxGiG1ihj1a8rzAtQE8JDFQezzVEDRKXu9iwCCxwpGnila8n3yTnZqHTdZCgBi94UcK7YBLOyy+jxq4oAgtZ5hN4lQSSCCwZu7HVBMyxMEu8mcDpJdRs80AJUlRqmhfRP0GuGS8kKIbjM8BiKKReqeld1YDXU1jvJBYjjNoe9eBvpcUUGGixBvYEHAbIBKnLaykHjaSSTVNnmUIcFIftBqRqPui7LyktTpTaElQdXqJgdKU1CXIBLkHF6H5X5uSicLRPTrZKkUp2pPvrHJWSSGe0z1M+Kk7GqyQ+2AW2bKM6YQiXOTfrVcogOFF2ZWzV2YhwYhlZZmEAm0MW5os00glgcahTOKggV7WDpOSyzcYnmpIJUhw4SGDJZtHW/OMcTkouCbRPLF2KkgHChupBakAml5bUWJtKXZIITZ5ykhTl2UwJxHdqrEicqTSm9xlLO1LNOcFwAwfCuJGvshmckKJfjVowRQKlgOhnNEO6iHVqLmgj1yUp1HjM/SSU85DJcuFJBTQjD51eAUyMtF3NqSpGiaWeZzTqChtCTU4VPu8Ly0oU40gukMUyJjgqRfQdYLhaPc42w0m5EUXa2WlIZgAqVo6CU0vSyTUFVXqo6mAkXkklV7jE8DUkKQEj5XXPzJwgFq8qrACjaEgXHLWeaSVBagSA+iGDM5OtwMYZeWVukqtQYlIKeLTAqigVNUsCC1Xx2w2lZIUkNxqeaEOpSCoaJAY3cQ7uQTQdr+jktZU/GZzAMwKBUqUXJu7FACmoYwCqflZaUA8ZcsouLNMJVcuk0wFFDY70j0rKcxyOMpBSoJP8AxppD1SxY1DpUXBpR+17ZLKUFRM2ZMvF2XdZNSWTdSKVar0SIswGXlZYWQprSlkJSCeLzSSo3U3qACq1YAGlY6ctkXntALaIazzOcSNTuWGPvEaeCAr5PniZLSsElxiUlLkUJuqqKgxYgggEGYV2d58IItQQF9UyEMjIC0pu8amHSSXIF4JS2ik+y7BziWD635BFpm01myKpLPPUsi6XI9pN0PjQEISCBjpHFRgsORVSlBWfUtgoMsPziC7gioFHxrizAEEFXMo5VzRToXnfW2DdnbFP+JPyvu/1BBAsfxJ+V93+oP4k/K+7/AFBBBLH8Sflfd/qD+JPyvu/1BBAsfxJ+V93+oP4k/K+7/UEECx/En5X3f6izk/LOcVduNQl7z7OztjsEKLMM72Qpn5KUpZXnlAFQXdAoec4VXSBStSd3oiCCFFp8m2MyaXrw9zHUzl64Hv77+d7IIIFo7ObqUpxYAOcSwZzBPN5JTg+Pu1j5inzgggWkzvZBneyCCFFjO9kGd7IIIUWoQQQRagt//9k=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNHO2Aw5ON3Eb0VKcT_H6IU3GoJQk-0fS9FJri--fYbcQJSMCN

Thanks!

**Comment by ssricardo** [comment]
Hello.
Thanks for the report.

What is the version of your Anki?
Is "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNHO2Aw5ON3Eb0VKcT_H6IU3GoJQk-0fS9FJri--fYbcQJSMCN" the location of the image you are trying to download?

**Comment by ssricardo** [comment]
It's **not possible** to use this kind of URL.  
The addon uses Anki API to download the files. 
Anki checks for the file extension on the URL and accepts only some known extensions for images and audios. Therefore, it won't be possible to download from dynamic URLs which doesn't obey this rule. 

**Addon updated - Version 1.1**: 

* It checks whether it was possible to use the given URL
* It notifies the user if it wasn't possible to use it instead of showing the code (like in the issue)
