### ISSUE TITLE
Update breaks normal {{type:Back}} cards

### ISSUE THREAD

**Issue by lavedon** [ssricardo/anki-plugins#83]
Hello, 

I use this wonderful plugin alongside normal type answer cards without hints.  Meaning, I have both {{{type:cloze:Text}}}} cards using this plugin mixed with {{type:Back}} cards.  

After today's update.  No {{type:Back}} cards will work.  I only get an "Unknown Field" error, which is confusing.  When I disable the plugin, alas, the {{type:Back}} cards go back to working as normal.

By the by, 

Today's update would also crash Anki 2.1.35 -- which is fine.  It got me to finally update to 2.1.40.  Otherwise, besides the above issue, works great on 2.1.40 

Thank you for all your hard work on this wonderful plugin.

**Comment by vorand** [comment]
I got the same issue with {{type:Word}}  cards.

**Comment by ssricardo** [comment]
Hi @lavedon and @vorand 

Thanks for reporting. 
I just published a new version. It seems ok.

Can you update and let me know, please?!

**Comment by lavedon** [comment]
Great! will try now.

**Comment by lavedon** [comment]
Seems to work fine now! Thanks so much for fixing this! And for doing it so quickly as well! Much appreciated.

**Comment by ssricardo** [comment]
Great then!
Closing...
