### ISSUE TITLE
Colours after the latest update are poorly visible in light mode

### ISSUE THREAD

**Issue by SkyOfSteel** [ssricardo/anki-plugins#84]
Hello!

It seems that the latest plugin update changed the colour scheme of the answers - sadly, it makes them rather poorly visible on the white background - please see the screenshot.

Is there any chance to revert the change or let the users pick their own colours? Both green and yellow were more discernible in the previous version, and now I have trouble with them because of their low contrast.

![изображение](https://user-images.githubusercontent.com/79771225/109402417-c1347e00-7966-11eb-8ead-038881585508.png)

**Comment by ssricardo** [comment]
Humm, indeed. 

I'll try finding some color with fits both dark and light modes.

For while, you can change the colors on Note editor; addiing the rules:

```
    .cloze.st-error {
        color: #ff9999;
        text-decoration: line-through;
    }
    .cloze.st-expected {
        color: #FFFF77;
    }
    .cloze.st-ok {
        color: #99ff99;
    }
```

Then changing the colors, according to preference

**Comment by ssricardo** [comment]
Please update to version 2.2.

And apart of that you can still customize according to above comment
