### ISSUE TITLE
Feature request - ignore Hebrew vowels on feedback

### ISSUE THREAD

**Issue by eliyahuswitzer** [ssricardo/anki-plugins#86]
It would be really great to be able to ignore Hebrew vowels on the feedback. (E.g. instead of the displayed שָלוֹם, feedback should only look for שלום.  For example in the attached .zip file of an .apkg deck:
[Example.zip](https://github.com/ssricardo/anki-plugins/files/6075049/Example.zip)
there are 2 notes with 3 cards each. "ברכות ט ה 2/4 - Vowels" includes vowels, so if you type the second letter of a word without including vowels it will be considered wrong. I would want the feedback in the 2nd example, "ברכות ט ה 2/4 - Manually removed vowels," preferably automatically (where the note includes the vowels but the addon knows to ignore them).

**Comment by eliyahuswitzer** [comment]
Sorry, and one other request would be if it's possible to ignore "cantillation" symbols as well. I attached an example.
For reference a list of all of these are at: https://en.wikipedia.org/wiki/Hebrew_cantillation#Names_and_shapes_of_the_te'amim
For the vowels above, a list is here: https://en.wikipedia.org/wiki/Niqqud#Keyboard
[Example 2.zip](https://github.com/ssricardo/anki-plugins/files/6076423/Example.2.zip)
Let me know if I can help, I have some coding background as well, thanks!

**Comment by ssricardo** [comment]
Hey @eliyahuswitzer, 
I imported you sample-deck and tried to do something around this, but could not make any progress. 

I'll keep this issue open for now, so that, maybe some developer with knowledge with that can work on it...

**Comment by ssricardo** [comment]
This has been open for a while and it doesn't seem to be needed by anyone else. 
And as I couldn't reproduce/work on that, it won't be done for now.
