### ISSUE TITLE
Front card is not displayed on ankiweb.net

### ISSUE THREAD

**Issue by MadNoMad27** [ssricardo/anki-plugins#88]
Hi! I really loved the add-on but there is one issue. The note created with the add-on does not show the front card when reviewing on ankiweb.net, be it from the computer browser or the phone browser. There are no issues when reviewing on the desktop application. I tested it by enabling and disabling the add-on. So the notes created without the add-on (or disabled add-on) show the front card on ankiweb, while the cards created with the enabled add-on do not show the front side on ankiweb. After disabling the add-on, my cards that I previously created with the help of the add-on do not show the front side on ankiweb as well as on my desktop application. Here are the screenshots:
On Anki app on Mac:
![Screen Shot 2021-03-09 at 10 41 41 PM](https://user-images.githubusercontent.com/80362298/110543476-a7dfbe80-812a-11eb-93ea-5fc63f925dd9.png)
![Screen Shot 2021-03-09 at 10 41 58 PM](https://user-images.githubusercontent.com/80362298/110543501-af9f6300-812a-11eb-97a2-33e28d8f03d6.png)

On Ankiweb:
![Screen Shot 2021-03-09 at 10 42 21 PM](https://user-images.githubusercontent.com/80362298/110543795-0d33af80-812b-11eb-9eb6-d9861ba0b425.png)
![Screen Shot 2021-03-09 at 10 42 32 PM](https://user-images.githubusercontent.com/80362298/110543806-102ea000-812b-11eb-82d7-5a819c2c6e7c.png)

On Anki app after disabling the add-on:
![Screen Shot 2021-03-09 at 10 48 48 PM](https://user-images.githubusercontent.com/80362298/110543870-289eba80-812b-11eb-9f69-8d29bd2993c0.png)
![Screen Shot 2021-03-09 at 10 48 55 PM](https://user-images.githubusercontent.com/80362298/110543882-2ccad800-812b-11eb-91a1-25f4b18c76f6.png)

Thanks for the efforts! And I hope it can be fixed.

**Comment by ssricardo** [comment]
Hi!
Every Anki Add-ons work only over the Desktop version. 
All other device will continue working like Anki Desktop without the add-ons. 

So, unfortunately there's nothing that I can do about it. 
My suggestion (what I do) is to keep the cards focused on this Feature, in a separate Deck.
