### ISSUE TITLE
Changing Font Size of Input Text

### ISSUE THREAD

**Issue by mytestingsolution** [ssricardo/anki-plugins#89]
Extremely useful plugin! Thank you so much, it's been so helpful as I'm learning to code.

I read through the other issue re font size, but I've tried all of that code in the style section and just haven't gotten it to work. I spent about an hour reading on reddit, trying different things , but never could get it to go.

Any thoughts on how to do this?

Thanks!

**Comment by ssricardo** [comment]
Hi!
Which one do you mean? Fill the blanks?
If so, have you tried this: https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blank---Styles

**Comment by ssricardo** [comment]
I hope the wiki page helped. 
Closing the issue
