### ISSUE TITLE
Bug with inserting the [...] character sequence

### ISSUE THREAD

**Issue by pedro-volpi** [ssricardo/anki-plugins#90]
I have a couple of cards that use the [...] sequence in them, because of reasons.
If I insert the [...] character sequence on a cloze card, the app has a weird behaviour, switching positions of text fields.

Edit: Now I realize that you use this sequence to create the cards. I suggest patching it to use special characters or something more unusual. I changed the code in my computer to have the string "\_\_PLACEHOLDER\_\_" instead of "[...]". Cheers.

**Comment by ssricardo** [comment]
Hi!

Sorry that I didn't see it before, but I'm glad that you could figure it out by yourself.

It's exactly that... I use this sequence as sort of a "reserved string".

As you got it, I'll close this for now, ok?!
If you still have a problem, please just re-open it
