### ISSUE TITLE
Ignore-case option produces strikethtough on correct answers

### ISSUE THREAD

**Issue by pespinozav** [ssricardo/anki-plugins#92]
Hi! With the ignore-case option selected, I get a green color feedback while typing, but when I press enter, the answer is incorrectly marked with a strikethrough line.
![image](https://user-images.githubusercontent.com/22034819/115999491-d9103300-a5a0-11eb-93ae-2b15bcfdb571.png)

![image](https://user-images.githubusercontent.com/22034819/115999467-bda52800-a5a0-11eb-99a3-7fa323a3eab3.png)

Thanks!

**Comment by ssricardo** [comment]
Hi! There's a change on the way. I'll make it available soon

**Comment by pespinozav** [comment]
Thanks! It works nicely.
