### ISSUE TITLE
Longer answers and bigger font size when typing in an answer

### ISSUE THREAD

**Issue by vonnr** [ssricardo/anki-plugins#93]
Is there a way to allow for longer answers? Because I have been noticing that longer answers (a sentence) just appears to be in blue font, it does not display if it's correct or not. 
![image](https://user-images.githubusercontent.com/81969507/116501719-20b9f600-a8e4-11eb-975b-d228c4af66f4.png)

**Comment by ssricardo** [comment]
Hi!
Can you try this: https://github.com/ssricardo/anki-plugins/wiki/Fill-the-blank---Styles

**Comment by vonnr** [comment]
Hello
I already tried inserting it in the styling section and still doesn't seem
to make the font any larger.

**Comment by ssricardo** [comment]
I added the support for this, using a config.

Please update and check the configurations.
