### ISSUE TITLE
Typed and normal clozes

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [ssricardo/anki-plugins#99]
Maybe this isn't the best place to discuss this, but since I haven't found another way to contact you, I'll post it here.

I think the typed cloze idea is awesome so I've been using your Add-on for a while, but I've recently started using a specific type of template produced by https://forums.ankiweb.net/u/kleinerpirat on the anki forum, you can get more information here https://forums.ankiweb.net/t/anki-as-a-knowledge-base-with-a-massive-cloze-note/11658/38 and it gave me a great idea.

The point is that I would like to use typed cloze in this template, but not exactly the way your Add-on works. I would like to use normal cloze(no typing) and typed cloze on the same card, currently your add-on converts all normal cloze into typed.

This could be done through a syntax change.

For example:

If you could {{c1::help me}}, I would be immensely {{c1t::grateful}}.

Where {{c1::}} would indicate normal cloze and {{c1t::}} would indicate typed.

Or any other way that was effective.

I'm not a programmer, so I don't know if this would be too difficult to implement, but since your Add-on does something similar to what I need, I decided to contact you.

Even if you discredit my request, please let me know, i'm really looking forward to your answer.

**Comment by ssricardo** [comment]
Olá @Casartellii .

Já tenho planos de mudar a forma como o add-on usa os campos com os valores. 
Mas isso deve levar um tempo ainda, ok?!
Acho que algumas mudanças grandes devem ser necessárias...

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
Muito obrigado pela resposta! Fico no aguardo então.
